[2025-09-03T19:42:16.030+0200] {processor.py:153} INFO - Started process (PID=3083) to work on /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py
[2025-09-03T19:42:16.031+0200] {processor.py:743} INFO - Processing file /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py for tasks to queue
[2025-09-03T19:42:16.032+0200] {logging_mixin.py:137} INFO - [2025-09-03T19:42:16.031+0200] {dagbag.py:532} INFO - Filling up the DagBag from /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py
[2025-09-03T19:42:16.036+0200] {logging_mixin.py:137} INFO - [2025-09-03T19:42:16.034+0200] {dagbag.py:341} ERROR - Failed to import: /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py
Traceback (most recent call last):
  File "/home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py", line 24, in <module>
    from pandas.tseries.holiday import USFederalHolidayCalendar
ModuleNotFoundError: No module named 'pandas'
[2025-09-03T19:42:16.037+0200] {processor.py:755} WARNING - No viable dags retrieved from /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py
[2025-09-03T19:42:16.060+0200] {processor.py:175} INFO - Processing /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py took 0.034 seconds
[2025-09-03T19:43:09.431+0200] {processor.py:153} INFO - Started process (PID=3125) to work on /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py
[2025-09-03T19:43:09.432+0200] {processor.py:743} INFO - Processing file /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py for tasks to queue
[2025-09-03T19:43:09.433+0200] {logging_mixin.py:137} INFO - [2025-09-03T19:43:09.433+0200] {dagbag.py:532} INFO - Filling up the DagBag from /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py
[2025-09-03T19:43:09.436+0200] {logging_mixin.py:137} INFO - [2025-09-03T19:43:09.435+0200] {dagbag.py:341} ERROR - Failed to import: /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py
Traceback (most recent call last):
  File "/home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py", line 24, in <module>
    from pandas.tseries.holiday import USFederalHolidayCalendar
ModuleNotFoundError: No module named 'pandas'
[2025-09-03T19:43:09.437+0200] {processor.py:755} WARNING - No viable dags retrieved from /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py
[2025-09-03T19:43:09.456+0200] {processor.py:175} INFO - Processing /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py took 0.028 seconds
[2025-09-03T19:43:55.697+0200] {processor.py:153} INFO - Started process (PID=3167) to work on /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py
[2025-09-03T19:43:55.698+0200] {processor.py:743} INFO - Processing file /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py for tasks to queue
[2025-09-03T19:43:55.699+0200] {logging_mixin.py:137} INFO - [2025-09-03T19:43:55.699+0200] {dagbag.py:532} INFO - Filling up the DagBag from /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py
[2025-09-03T19:43:55.702+0200] {logging_mixin.py:137} INFO - [2025-09-03T19:43:55.701+0200] {dagbag.py:341} ERROR - Failed to import: /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py
Traceback (most recent call last):
  File "/home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py", line 24, in <module>
    from pandas.tseries.holiday import USFederalHolidayCalendar
ModuleNotFoundError: No module named 'pandas'
[2025-09-03T19:43:55.703+0200] {processor.py:755} WARNING - No viable dags retrieved from /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py
[2025-09-03T19:43:55.723+0200] {processor.py:175} INFO - Processing /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py took 0.029 seconds
[2025-09-03T19:44:43.306+0200] {processor.py:153} INFO - Started process (PID=3209) to work on /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py
[2025-09-03T19:44:43.308+0200] {processor.py:743} INFO - Processing file /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py for tasks to queue
[2025-09-03T19:44:43.310+0200] {logging_mixin.py:137} INFO - [2025-09-03T19:44:43.309+0200] {dagbag.py:532} INFO - Filling up the DagBag from /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py
[2025-09-03T19:44:43.315+0200] {logging_mixin.py:137} INFO - [2025-09-03T19:44:43.314+0200] {dagbag.py:341} ERROR - Failed to import: /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py
Traceback (most recent call last):
  File "/home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py", line 24, in <module>
    from pandas.tseries.holiday import USFederalHolidayCalendar
ModuleNotFoundError: No module named 'pandas'
[2025-09-03T19:44:43.316+0200] {processor.py:755} WARNING - No viable dags retrieved from /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py
[2025-09-03T19:44:43.350+0200] {processor.py:175} INFO - Processing /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py took 0.050 seconds
[2025-09-03T19:45:33.608+0200] {processor.py:153} INFO - Started process (PID=3280) to work on /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py
[2025-09-03T19:45:33.610+0200] {processor.py:743} INFO - Processing file /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py for tasks to queue
[2025-09-03T19:45:33.611+0200] {logging_mixin.py:137} INFO - [2025-09-03T19:45:33.611+0200] {dagbag.py:532} INFO - Filling up the DagBag from /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py
[2025-09-03T19:45:33.614+0200] {logging_mixin.py:137} INFO - [2025-09-03T19:45:33.613+0200] {dagbag.py:341} ERROR - Failed to import: /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py
Traceback (most recent call last):
  File "/home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py", line 24, in <module>
    from pandas.tseries.holiday import USFederalHolidayCalendar
ModuleNotFoundError: No module named 'pandas'
[2025-09-03T19:45:33.614+0200] {processor.py:755} WARNING - No viable dags retrieved from /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py
[2025-09-03T19:45:33.632+0200] {processor.py:175} INFO - Processing /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py took 0.027 seconds
[2025-09-03T19:46:18.204+0200] {processor.py:153} INFO - Started process (PID=3322) to work on /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py
[2025-09-03T19:46:18.206+0200] {processor.py:743} INFO - Processing file /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py for tasks to queue
[2025-09-03T19:46:18.206+0200] {logging_mixin.py:137} INFO - [2025-09-03T19:46:18.206+0200] {dagbag.py:532} INFO - Filling up the DagBag from /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py
[2025-09-03T19:46:18.209+0200] {logging_mixin.py:137} INFO - [2025-09-03T19:46:18.208+0200] {dagbag.py:341} ERROR - Failed to import: /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py
Traceback (most recent call last):
  File "/home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py", line 24, in <module>
    from pandas.tseries.holiday import USFederalHolidayCalendar
ModuleNotFoundError: No module named 'pandas'
[2025-09-03T19:46:18.209+0200] {processor.py:755} WARNING - No viable dags retrieved from /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py
[2025-09-03T19:46:18.229+0200] {processor.py:175} INFO - Processing /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py took 0.028 seconds
[2025-09-03T19:47:02.816+0200] {processor.py:153} INFO - Started process (PID=3374) to work on /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py
[2025-09-03T19:47:02.820+0200] {processor.py:743} INFO - Processing file /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py for tasks to queue
[2025-09-03T19:47:02.821+0200] {logging_mixin.py:137} INFO - [2025-09-03T19:47:02.821+0200] {dagbag.py:532} INFO - Filling up the DagBag from /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py
[2025-09-03T19:47:02.829+0200] {logging_mixin.py:137} INFO - [2025-09-03T19:47:02.827+0200] {dagbag.py:341} ERROR - Failed to import: /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py
Traceback (most recent call last):
  File "/home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py", line 24, in <module>
    from pandas.tseries.holiday import USFederalHolidayCalendar
ModuleNotFoundError: No module named 'pandas'
[2025-09-03T19:47:02.830+0200] {processor.py:755} WARNING - No viable dags retrieved from /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py
[2025-09-03T19:47:02.886+0200] {processor.py:175} INFO - Processing /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py took 0.079 seconds
[2025-09-03T19:47:52.003+0200] {processor.py:153} INFO - Started process (PID=3420) to work on /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py
[2025-09-03T19:47:52.005+0200] {processor.py:743} INFO - Processing file /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py for tasks to queue
[2025-09-03T19:47:52.005+0200] {logging_mixin.py:137} INFO - [2025-09-03T19:47:52.005+0200] {dagbag.py:532} INFO - Filling up the DagBag from /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py
[2025-09-03T19:47:52.008+0200] {logging_mixin.py:137} INFO - [2025-09-03T19:47:52.007+0200] {dagbag.py:341} ERROR - Failed to import: /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py
Traceback (most recent call last):
  File "/home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py", line 24, in <module>
    from pandas.tseries.holiday import USFederalHolidayCalendar
ModuleNotFoundError: No module named 'pandas'
[2025-09-03T19:47:52.008+0200] {processor.py:755} WARNING - No viable dags retrieved from /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py
[2025-09-03T19:47:52.030+0200] {processor.py:175} INFO - Processing /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py took 0.029 seconds
[2025-09-03T19:48:39.681+0200] {processor.py:153} INFO - Started process (PID=3462) to work on /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py
[2025-09-03T19:48:39.683+0200] {processor.py:743} INFO - Processing file /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py for tasks to queue
[2025-09-03T19:48:39.684+0200] {logging_mixin.py:137} INFO - [2025-09-03T19:48:39.683+0200] {dagbag.py:532} INFO - Filling up the DagBag from /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py
[2025-09-03T19:48:39.686+0200] {logging_mixin.py:137} INFO - [2025-09-03T19:48:39.685+0200] {dagbag.py:341} ERROR - Failed to import: /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py
Traceback (most recent call last):
  File "/home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py", line 24, in <module>
    from pandas.tseries.holiday import USFederalHolidayCalendar
ModuleNotFoundError: No module named 'pandas'
[2025-09-03T19:48:39.686+0200] {processor.py:755} WARNING - No viable dags retrieved from /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py
[2025-09-03T19:48:39.705+0200] {processor.py:175} INFO - Processing /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py took 0.028 seconds
[2025-09-03T19:49:27.755+0200] {processor.py:153} INFO - Started process (PID=3504) to work on /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py
[2025-09-03T19:49:27.757+0200] {processor.py:743} INFO - Processing file /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py for tasks to queue
[2025-09-03T19:49:27.758+0200] {logging_mixin.py:137} INFO - [2025-09-03T19:49:27.758+0200] {dagbag.py:532} INFO - Filling up the DagBag from /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py
[2025-09-03T19:49:27.761+0200] {logging_mixin.py:137} INFO - [2025-09-03T19:49:27.760+0200] {dagbag.py:341} ERROR - Failed to import: /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py
Traceback (most recent call last):
  File "/home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py", line 24, in <module>
    from pandas.tseries.holiday import USFederalHolidayCalendar
ModuleNotFoundError: No module named 'pandas'
[2025-09-03T19:49:27.762+0200] {processor.py:755} WARNING - No viable dags retrieved from /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py
[2025-09-03T19:49:27.794+0200] {processor.py:175} INFO - Processing /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py took 0.044 seconds
[2025-09-03T19:50:18.504+0200] {processor.py:153} INFO - Started process (PID=3555) to work on /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py
[2025-09-03T19:50:18.506+0200] {processor.py:743} INFO - Processing file /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py for tasks to queue
[2025-09-03T19:50:18.506+0200] {logging_mixin.py:137} INFO - [2025-09-03T19:50:18.506+0200] {dagbag.py:532} INFO - Filling up the DagBag from /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py
[2025-09-03T19:50:18.511+0200] {logging_mixin.py:137} INFO - [2025-09-03T19:50:18.510+0200] {dagbag.py:341} ERROR - Failed to import: /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py
Traceback (most recent call last):
  File "/home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py", line 24, in <module>
    from pandas.tseries.holiday import USFederalHolidayCalendar
ModuleNotFoundError: No module named 'pandas'
[2025-09-03T19:50:18.511+0200] {processor.py:755} WARNING - No viable dags retrieved from /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py
[2025-09-03T19:50:18.536+0200] {processor.py:175} INFO - Processing /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py took 0.036 seconds
[2025-09-03T19:51:03.951+0200] {processor.py:153} INFO - Started process (PID=3605) to work on /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py
[2025-09-03T19:51:03.952+0200] {processor.py:743} INFO - Processing file /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py for tasks to queue
[2025-09-03T19:51:03.953+0200] {logging_mixin.py:137} INFO - [2025-09-03T19:51:03.953+0200] {dagbag.py:532} INFO - Filling up the DagBag from /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py
[2025-09-03T19:51:03.956+0200] {logging_mixin.py:137} INFO - [2025-09-03T19:51:03.955+0200] {dagbag.py:341} ERROR - Failed to import: /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py
Traceback (most recent call last):
  File "/home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py", line 24, in <module>
    from pandas.tseries.holiday import USFederalHolidayCalendar
ModuleNotFoundError: No module named 'pandas'
[2025-09-03T19:51:03.956+0200] {processor.py:755} WARNING - No viable dags retrieved from /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py
[2025-09-03T19:51:03.980+0200] {processor.py:175} INFO - Processing /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py took 0.032 seconds
[2025-09-03T19:51:50.095+0200] {processor.py:153} INFO - Started process (PID=3656) to work on /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py
[2025-09-03T19:51:50.097+0200] {processor.py:743} INFO - Processing file /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py for tasks to queue
[2025-09-03T19:51:50.098+0200] {logging_mixin.py:137} INFO - [2025-09-03T19:51:50.098+0200] {dagbag.py:532} INFO - Filling up the DagBag from /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py
[2025-09-03T19:51:50.101+0200] {logging_mixin.py:137} INFO - [2025-09-03T19:51:50.100+0200] {dagbag.py:341} ERROR - Failed to import: /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py
Traceback (most recent call last):
  File "/home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py", line 24, in <module>
    from pandas.tseries.holiday import USFederalHolidayCalendar
ModuleNotFoundError: No module named 'pandas'
[2025-09-03T19:51:50.101+0200] {processor.py:755} WARNING - No viable dags retrieved from /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py
[2025-09-03T19:51:50.125+0200] {processor.py:175} INFO - Processing /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py took 0.033 seconds
[2025-09-03T19:52:44.625+0200] {processor.py:153} INFO - Started process (PID=3702) to work on /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py
[2025-09-03T19:52:44.626+0200] {processor.py:743} INFO - Processing file /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py for tasks to queue
[2025-09-03T19:52:44.627+0200] {logging_mixin.py:137} INFO - [2025-09-03T19:52:44.627+0200] {dagbag.py:532} INFO - Filling up the DagBag from /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py
[2025-09-03T19:52:44.632+0200] {logging_mixin.py:137} INFO - [2025-09-03T19:52:44.630+0200] {dagbag.py:341} ERROR - Failed to import: /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py
Traceback (most recent call last):
  File "/home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py", line 24, in <module>
    from pandas.tseries.holiday import USFederalHolidayCalendar
ModuleNotFoundError: No module named 'pandas'
[2025-09-03T19:52:44.632+0200] {processor.py:755} WARNING - No viable dags retrieved from /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py
[2025-09-03T19:52:44.659+0200] {processor.py:175} INFO - Processing /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py took 0.038 seconds
[2025-09-03T19:53:34.029+0200] {processor.py:153} INFO - Started process (PID=3744) to work on /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py
[2025-09-03T19:53:34.031+0200] {processor.py:743} INFO - Processing file /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py for tasks to queue
[2025-09-03T19:53:34.032+0200] {logging_mixin.py:137} INFO - [2025-09-03T19:53:34.032+0200] {dagbag.py:532} INFO - Filling up the DagBag from /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py
[2025-09-03T19:53:34.037+0200] {logging_mixin.py:137} INFO - [2025-09-03T19:53:34.035+0200] {dagbag.py:341} ERROR - Failed to import: /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py
Traceback (most recent call last):
  File "/home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py", line 24, in <module>
    from pandas.tseries.holiday import USFederalHolidayCalendar
ModuleNotFoundError: No module named 'pandas'
[2025-09-03T19:53:34.038+0200] {processor.py:755} WARNING - No viable dags retrieved from /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py
[2025-09-03T19:53:34.069+0200] {processor.py:175} INFO - Processing /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py took 0.045 seconds
[2025-09-03T19:54:36.184+0200] {processor.py:153} INFO - Started process (PID=3797) to work on /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py
[2025-09-03T19:54:36.187+0200] {processor.py:743} INFO - Processing file /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py for tasks to queue
[2025-09-03T19:54:36.188+0200] {logging_mixin.py:137} INFO - [2025-09-03T19:54:36.188+0200] {dagbag.py:532} INFO - Filling up the DagBag from /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py
[2025-09-03T19:54:36.192+0200] {logging_mixin.py:137} INFO - [2025-09-03T19:54:36.190+0200] {dagbag.py:341} ERROR - Failed to import: /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py
Traceback (most recent call last):
  File "/home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py", line 24, in <module>
    from pandas.tseries.holiday import USFederalHolidayCalendar
ModuleNotFoundError: No module named 'pandas'
[2025-09-03T19:54:36.192+0200] {processor.py:755} WARNING - No viable dags retrieved from /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py
[2025-09-03T19:54:36.219+0200] {processor.py:175} INFO - Processing /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py took 0.040 seconds
[2025-09-03T19:55:31.367+0200] {processor.py:153} INFO - Started process (PID=3853) to work on /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py
[2025-09-03T19:55:31.369+0200] {processor.py:743} INFO - Processing file /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py for tasks to queue
[2025-09-03T19:55:31.369+0200] {logging_mixin.py:137} INFO - [2025-09-03T19:55:31.369+0200] {dagbag.py:532} INFO - Filling up the DagBag from /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py
[2025-09-03T19:55:31.372+0200] {logging_mixin.py:137} INFO - [2025-09-03T19:55:31.371+0200] {dagbag.py:341} ERROR - Failed to import: /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py
Traceback (most recent call last):
  File "/home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py", line 24, in <module>
    from pandas.tseries.holiday import USFederalHolidayCalendar
ModuleNotFoundError: No module named 'pandas'
[2025-09-03T19:55:31.372+0200] {processor.py:755} WARNING - No viable dags retrieved from /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py
[2025-09-03T19:55:31.394+0200] {processor.py:175} INFO - Processing /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py took 0.030 seconds
[2025-09-03T19:56:32.826+0200] {processor.py:153} INFO - Started process (PID=3903) to work on /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py
[2025-09-03T19:56:32.828+0200] {processor.py:743} INFO - Processing file /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py for tasks to queue
[2025-09-03T19:56:32.829+0200] {logging_mixin.py:137} INFO - [2025-09-03T19:56:32.829+0200] {dagbag.py:532} INFO - Filling up the DagBag from /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py
[2025-09-03T19:56:32.831+0200] {logging_mixin.py:137} INFO - [2025-09-03T19:56:32.831+0200] {dagbag.py:341} ERROR - Failed to import: /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py
Traceback (most recent call last):
  File "/home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py", line 24, in <module>
    from pandas.tseries.holiday import USFederalHolidayCalendar
ModuleNotFoundError: No module named 'pandas'
[2025-09-03T19:56:32.832+0200] {processor.py:755} WARNING - No viable dags retrieved from /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py
[2025-09-03T19:56:32.856+0200] {processor.py:175} INFO - Processing /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py took 0.033 seconds
[2025-09-03T19:57:28.124+0200] {processor.py:153} INFO - Started process (PID=3950) to work on /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py
[2025-09-03T19:57:28.131+0200] {processor.py:743} INFO - Processing file /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py for tasks to queue
[2025-09-03T19:57:28.133+0200] {logging_mixin.py:137} INFO - [2025-09-03T19:57:28.132+0200] {dagbag.py:532} INFO - Filling up the DagBag from /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py
[2025-09-03T19:57:28.140+0200] {logging_mixin.py:137} INFO - [2025-09-03T19:57:28.138+0200] {dagbag.py:341} ERROR - Failed to import: /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py
Traceback (most recent call last):
  File "/home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py", line 24, in <module>
    from pandas.tseries.holiday import USFederalHolidayCalendar
ModuleNotFoundError: No module named 'pandas'
[2025-09-03T19:57:28.141+0200] {processor.py:755} WARNING - No viable dags retrieved from /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py
[2025-09-03T19:57:28.193+0200] {processor.py:175} INFO - Processing /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py took 0.083 seconds
[2025-09-03T19:58:16.866+0200] {processor.py:153} INFO - Started process (PID=3992) to work on /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py
[2025-09-03T19:58:16.869+0200] {processor.py:743} INFO - Processing file /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py for tasks to queue
[2025-09-03T19:58:16.870+0200] {logging_mixin.py:137} INFO - [2025-09-03T19:58:16.869+0200] {dagbag.py:532} INFO - Filling up the DagBag from /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py
[2025-09-03T19:58:16.874+0200] {logging_mixin.py:137} INFO - [2025-09-03T19:58:16.872+0200] {dagbag.py:341} ERROR - Failed to import: /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py
Traceback (most recent call last):
  File "/home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py", line 24, in <module>
    from pandas.tseries.holiday import USFederalHolidayCalendar
ModuleNotFoundError: No module named 'pandas'
[2025-09-03T19:58:16.874+0200] {processor.py:755} WARNING - No viable dags retrieved from /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py
[2025-09-03T19:58:16.902+0200] {processor.py:175} INFO - Processing /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py took 0.040 seconds
[2025-09-03T20:00:34.170+0200] {processor.py:153} INFO - Started process (PID=4010) to work on /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py
[2025-09-03T20:00:34.171+0200] {processor.py:743} INFO - Processing file /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py for tasks to queue
[2025-09-03T20:00:34.171+0200] {logging_mixin.py:137} INFO - [2025-09-03T20:00:34.171+0200] {dagbag.py:532} INFO - Filling up the DagBag from /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py
[2025-09-03T20:00:34.175+0200] {logging_mixin.py:137} INFO - [2025-09-03T20:00:34.174+0200] {dagbag.py:341} ERROR - Failed to import: /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py
Traceback (most recent call last):
  File "/home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py", line 24, in <module>
    from pandas.tseries.holiday import USFederalHolidayCalendar
ModuleNotFoundError: No module named 'pandas'
[2025-09-03T20:00:34.175+0200] {processor.py:755} WARNING - No viable dags retrieved from /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py
[2025-09-03T20:00:34.196+0200] {processor.py:175} INFO - Processing /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py took 0.030 seconds
[2025-09-03T20:01:20.462+0200] {processor.py:153} INFO - Started process (PID=4067) to work on /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py
[2025-09-03T20:01:20.463+0200] {processor.py:743} INFO - Processing file /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py for tasks to queue
[2025-09-03T20:01:20.464+0200] {logging_mixin.py:137} INFO - [2025-09-03T20:01:20.464+0200] {dagbag.py:532} INFO - Filling up the DagBag from /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py
[2025-09-03T20:01:20.468+0200] {logging_mixin.py:137} INFO - [2025-09-03T20:01:20.466+0200] {dagbag.py:341} ERROR - Failed to import: /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py
Traceback (most recent call last):
  File "/home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py", line 24, in <module>
    from pandas.tseries.holiday import USFederalHolidayCalendar
ModuleNotFoundError: No module named 'pandas'
[2025-09-03T20:01:20.468+0200] {processor.py:755} WARNING - No viable dags retrieved from /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py
[2025-09-03T20:01:20.497+0200] {processor.py:175} INFO - Processing /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py took 0.040 seconds
[2025-09-03T20:02:06.612+0200] {processor.py:153} INFO - Started process (PID=4110) to work on /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py
[2025-09-03T20:02:06.614+0200] {processor.py:743} INFO - Processing file /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py for tasks to queue
[2025-09-03T20:02:06.614+0200] {logging_mixin.py:137} INFO - [2025-09-03T20:02:06.614+0200] {dagbag.py:532} INFO - Filling up the DagBag from /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py
[2025-09-03T20:02:06.617+0200] {logging_mixin.py:137} INFO - [2025-09-03T20:02:06.616+0200] {dagbag.py:341} ERROR - Failed to import: /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py
Traceback (most recent call last):
  File "/home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py", line 24, in <module>
    from pandas.tseries.holiday import USFederalHolidayCalendar
ModuleNotFoundError: No module named 'pandas'
[2025-09-03T20:02:06.617+0200] {processor.py:755} WARNING - No viable dags retrieved from /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py
[2025-09-03T20:02:06.638+0200] {processor.py:175} INFO - Processing /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py took 0.029 seconds
[2025-09-03T20:02:55.987+0200] {processor.py:153} INFO - Started process (PID=4152) to work on /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py
[2025-09-03T20:02:55.988+0200] {processor.py:743} INFO - Processing file /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py for tasks to queue
[2025-09-03T20:02:55.989+0200] {logging_mixin.py:137} INFO - [2025-09-03T20:02:55.989+0200] {dagbag.py:532} INFO - Filling up the DagBag from /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py
[2025-09-03T20:02:55.991+0200] {logging_mixin.py:137} INFO - [2025-09-03T20:02:55.990+0200] {dagbag.py:341} ERROR - Failed to import: /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py
Traceback (most recent call last):
  File "/home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py", line 24, in <module>
    from pandas.tseries.holiday import USFederalHolidayCalendar
ModuleNotFoundError: No module named 'pandas'
[2025-09-03T20:02:55.992+0200] {processor.py:755} WARNING - No viable dags retrieved from /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py
[2025-09-03T20:02:56.011+0200] {processor.py:175} INFO - Processing /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py took 0.028 seconds
[2025-09-03T20:03:43.159+0200] {processor.py:153} INFO - Started process (PID=4194) to work on /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py
[2025-09-03T20:03:43.161+0200] {processor.py:743} INFO - Processing file /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py for tasks to queue
[2025-09-03T20:03:43.161+0200] {logging_mixin.py:137} INFO - [2025-09-03T20:03:43.161+0200] {dagbag.py:532} INFO - Filling up the DagBag from /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py
[2025-09-03T20:03:43.164+0200] {logging_mixin.py:137} INFO - [2025-09-03T20:03:43.164+0200] {dagbag.py:341} ERROR - Failed to import: /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py
Traceback (most recent call last):
  File "/home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py", line 24, in <module>
    from pandas.tseries.holiday import USFederalHolidayCalendar
ModuleNotFoundError: No module named 'pandas'
[2025-09-03T20:03:43.165+0200] {processor.py:755} WARNING - No viable dags retrieved from /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py
[2025-09-03T20:03:43.185+0200] {processor.py:175} INFO - Processing /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py took 0.029 seconds
[2025-09-03T20:04:29.379+0200] {processor.py:153} INFO - Started process (PID=4236) to work on /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py
[2025-09-03T20:04:29.381+0200] {processor.py:743} INFO - Processing file /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py for tasks to queue
[2025-09-03T20:04:29.381+0200] {logging_mixin.py:137} INFO - [2025-09-03T20:04:29.381+0200] {dagbag.py:532} INFO - Filling up the DagBag from /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py
[2025-09-03T20:04:29.385+0200] {logging_mixin.py:137} INFO - [2025-09-03T20:04:29.383+0200] {dagbag.py:341} ERROR - Failed to import: /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py
Traceback (most recent call last):
  File "/home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py", line 24, in <module>
    from pandas.tseries.holiday import USFederalHolidayCalendar
ModuleNotFoundError: No module named 'pandas'
[2025-09-03T20:04:29.385+0200] {processor.py:755} WARNING - No viable dags retrieved from /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py
[2025-09-03T20:04:29.405+0200] {processor.py:175} INFO - Processing /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py took 0.029 seconds
[2025-09-03T20:05:31.805+0200] {processor.py:153} INFO - Started process (PID=4297) to work on /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py
[2025-09-03T20:05:31.807+0200] {processor.py:743} INFO - Processing file /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py for tasks to queue
[2025-09-03T20:05:31.808+0200] {logging_mixin.py:137} INFO - [2025-09-03T20:05:31.808+0200] {dagbag.py:532} INFO - Filling up the DagBag from /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py
[2025-09-03T20:05:31.812+0200] {logging_mixin.py:137} INFO - [2025-09-03T20:05:31.810+0200] {dagbag.py:341} ERROR - Failed to import: /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py
Traceback (most recent call last):
  File "/home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py", line 24, in <module>
    from pandas.tseries.holiday import USFederalHolidayCalendar
ModuleNotFoundError: No module named 'pandas'
[2025-09-03T20:05:31.812+0200] {processor.py:755} WARNING - No viable dags retrieved from /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py
[2025-09-03T20:05:31.838+0200] {processor.py:175} INFO - Processing /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py took 0.036 seconds
[2025-09-03T20:06:22.318+0200] {processor.py:153} INFO - Started process (PID=4339) to work on /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py
[2025-09-03T20:06:22.319+0200] {processor.py:743} INFO - Processing file /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py for tasks to queue
[2025-09-03T20:06:22.320+0200] {logging_mixin.py:137} INFO - [2025-09-03T20:06:22.320+0200] {dagbag.py:532} INFO - Filling up the DagBag from /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py
[2025-09-03T20:06:22.324+0200] {logging_mixin.py:137} INFO - [2025-09-03T20:06:22.323+0200] {dagbag.py:341} ERROR - Failed to import: /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py
Traceback (most recent call last):
  File "/home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py", line 24, in <module>
    from pandas.tseries.holiday import USFederalHolidayCalendar
ModuleNotFoundError: No module named 'pandas'
[2025-09-03T20:06:22.325+0200] {processor.py:755} WARNING - No viable dags retrieved from /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py
[2025-09-03T20:06:22.371+0200] {processor.py:175} INFO - Processing /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py took 0.057 seconds
[2025-09-03T20:07:09.081+0200] {processor.py:153} INFO - Started process (PID=4397) to work on /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py
[2025-09-03T20:07:09.082+0200] {processor.py:743} INFO - Processing file /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py for tasks to queue
[2025-09-03T20:07:09.083+0200] {logging_mixin.py:137} INFO - [2025-09-03T20:07:09.083+0200] {dagbag.py:532} INFO - Filling up the DagBag from /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py
[2025-09-03T20:07:09.088+0200] {logging_mixin.py:137} INFO - [2025-09-03T20:07:09.086+0200] {dagbag.py:341} ERROR - Failed to import: /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py
Traceback (most recent call last):
  File "/home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py", line 24, in <module>
    from pandas.tseries.holiday import USFederalHolidayCalendar
ModuleNotFoundError: No module named 'pandas'
[2025-09-03T20:07:09.088+0200] {processor.py:755} WARNING - No viable dags retrieved from /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py
[2025-09-03T20:07:09.131+0200] {processor.py:175} INFO - Processing /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py took 0.055 seconds
[2025-09-03T20:07:55.780+0200] {processor.py:153} INFO - Started process (PID=4449) to work on /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py
[2025-09-03T20:07:55.782+0200] {processor.py:743} INFO - Processing file /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py for tasks to queue
[2025-09-03T20:07:55.783+0200] {logging_mixin.py:137} INFO - [2025-09-03T20:07:55.783+0200] {dagbag.py:532} INFO - Filling up the DagBag from /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py
[2025-09-03T20:07:55.786+0200] {logging_mixin.py:137} INFO - [2025-09-03T20:07:55.785+0200] {dagbag.py:341} ERROR - Failed to import: /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py
Traceback (most recent call last):
  File "/home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py", line 24, in <module>
    from pandas.tseries.holiday import USFederalHolidayCalendar
ModuleNotFoundError: No module named 'pandas'
[2025-09-03T20:07:55.787+0200] {processor.py:755} WARNING - No viable dags retrieved from /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py
[2025-09-03T20:07:55.810+0200] {processor.py:175} INFO - Processing /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py took 0.033 seconds
[2025-09-03T20:09:10.676+0200] {processor.py:153} INFO - Started process (PID=4501) to work on /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py
[2025-09-03T20:09:10.678+0200] {processor.py:743} INFO - Processing file /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py for tasks to queue
[2025-09-03T20:09:10.679+0200] {logging_mixin.py:137} INFO - [2025-09-03T20:09:10.679+0200] {dagbag.py:532} INFO - Filling up the DagBag from /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py
[2025-09-03T20:09:10.683+0200] {logging_mixin.py:137} INFO - [2025-09-03T20:09:10.682+0200] {dagbag.py:341} ERROR - Failed to import: /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py
Traceback (most recent call last):
  File "/home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py", line 24, in <module>
    from pandas.tseries.holiday import USFederalHolidayCalendar
ModuleNotFoundError: No module named 'pandas'
[2025-09-03T20:09:10.684+0200] {processor.py:755} WARNING - No viable dags retrieved from /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py
[2025-09-03T20:09:10.712+0200] {processor.py:175} INFO - Processing /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py took 0.044 seconds
[2025-09-03T20:10:03.419+0200] {processor.py:153} INFO - Started process (PID=4550) to work on /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py
[2025-09-03T20:10:03.421+0200] {processor.py:743} INFO - Processing file /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py for tasks to queue
[2025-09-03T20:10:03.421+0200] {logging_mixin.py:137} INFO - [2025-09-03T20:10:03.421+0200] {dagbag.py:532} INFO - Filling up the DagBag from /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py
[2025-09-03T20:10:03.424+0200] {logging_mixin.py:137} INFO - [2025-09-03T20:10:03.424+0200] {dagbag.py:341} ERROR - Failed to import: /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py
Traceback (most recent call last):
  File "/home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py", line 24, in <module>
    from pandas.tseries.holiday import USFederalHolidayCalendar
ModuleNotFoundError: No module named 'pandas'
[2025-09-03T20:10:03.425+0200] {processor.py:755} WARNING - No viable dags retrieved from /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py
[2025-09-03T20:10:03.453+0200] {processor.py:175} INFO - Processing /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py took 0.040 seconds
[2025-09-03T20:10:48.032+0200] {processor.py:153} INFO - Started process (PID=4592) to work on /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py
[2025-09-03T20:10:48.034+0200] {processor.py:743} INFO - Processing file /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py for tasks to queue
[2025-09-03T20:10:48.034+0200] {logging_mixin.py:137} INFO - [2025-09-03T20:10:48.034+0200] {dagbag.py:532} INFO - Filling up the DagBag from /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py
[2025-09-03T20:10:48.037+0200] {logging_mixin.py:137} INFO - [2025-09-03T20:10:48.036+0200] {dagbag.py:341} ERROR - Failed to import: /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py
Traceback (most recent call last):
  File "/home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py", line 24, in <module>
    from pandas.tseries.holiday import USFederalHolidayCalendar
ModuleNotFoundError: No module named 'pandas'
[2025-09-03T20:10:48.037+0200] {processor.py:755} WARNING - No viable dags retrieved from /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py
[2025-09-03T20:10:48.060+0200] {processor.py:175} INFO - Processing /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py took 0.030 seconds
[2025-09-03T20:11:33.410+0200] {processor.py:153} INFO - Started process (PID=4634) to work on /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py
[2025-09-03T20:11:33.412+0200] {processor.py:743} INFO - Processing file /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py for tasks to queue
[2025-09-03T20:11:33.412+0200] {logging_mixin.py:137} INFO - [2025-09-03T20:11:33.412+0200] {dagbag.py:532} INFO - Filling up the DagBag from /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py
[2025-09-03T20:11:33.415+0200] {logging_mixin.py:137} INFO - [2025-09-03T20:11:33.414+0200] {dagbag.py:341} ERROR - Failed to import: /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py
Traceback (most recent call last):
  File "/home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py", line 24, in <module>
    from pandas.tseries.holiday import USFederalHolidayCalendar
ModuleNotFoundError: No module named 'pandas'
[2025-09-03T20:11:33.416+0200] {processor.py:755} WARNING - No viable dags retrieved from /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py
[2025-09-03T20:11:33.438+0200] {processor.py:175} INFO - Processing /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py took 0.030 seconds
[2025-09-03T20:12:21.912+0200] {processor.py:153} INFO - Started process (PID=4676) to work on /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py
[2025-09-03T20:12:21.913+0200] {processor.py:743} INFO - Processing file /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py for tasks to queue
[2025-09-03T20:12:21.914+0200] {logging_mixin.py:137} INFO - [2025-09-03T20:12:21.914+0200] {dagbag.py:532} INFO - Filling up the DagBag from /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py
[2025-09-03T20:12:21.917+0200] {logging_mixin.py:137} INFO - [2025-09-03T20:12:21.916+0200] {dagbag.py:341} ERROR - Failed to import: /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py
Traceback (most recent call last):
  File "/home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py", line 24, in <module>
    from pandas.tseries.holiday import USFederalHolidayCalendar
ModuleNotFoundError: No module named 'pandas'
[2025-09-03T20:12:21.917+0200] {processor.py:755} WARNING - No viable dags retrieved from /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py
[2025-09-03T20:12:21.938+0200] {processor.py:175} INFO - Processing /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py took 0.030 seconds
[2025-09-03T20:13:08.145+0200] {processor.py:153} INFO - Started process (PID=4719) to work on /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py
[2025-09-03T20:13:08.147+0200] {processor.py:743} INFO - Processing file /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py for tasks to queue
[2025-09-03T20:13:08.148+0200] {logging_mixin.py:137} INFO - [2025-09-03T20:13:08.148+0200] {dagbag.py:532} INFO - Filling up the DagBag from /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py
[2025-09-03T20:13:08.150+0200] {logging_mixin.py:137} INFO - [2025-09-03T20:13:08.149+0200] {dagbag.py:341} ERROR - Failed to import: /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py
Traceback (most recent call last):
  File "/home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py", line 24, in <module>
    from pandas.tseries.holiday import USFederalHolidayCalendar
ModuleNotFoundError: No module named 'pandas'
[2025-09-03T20:13:08.150+0200] {processor.py:755} WARNING - No viable dags retrieved from /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py
[2025-09-03T20:13:08.170+0200] {processor.py:175} INFO - Processing /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py took 0.028 seconds
[2025-09-03T20:13:54.319+0200] {processor.py:153} INFO - Started process (PID=4761) to work on /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py
[2025-09-03T20:13:54.321+0200] {processor.py:743} INFO - Processing file /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py for tasks to queue
[2025-09-03T20:13:54.321+0200] {logging_mixin.py:137} INFO - [2025-09-03T20:13:54.321+0200] {dagbag.py:532} INFO - Filling up the DagBag from /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py
[2025-09-03T20:13:54.324+0200] {logging_mixin.py:137} INFO - [2025-09-03T20:13:54.323+0200] {dagbag.py:341} ERROR - Failed to import: /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py
Traceback (most recent call last):
  File "/home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py", line 24, in <module>
    from pandas.tseries.holiday import USFederalHolidayCalendar
ModuleNotFoundError: No module named 'pandas'
[2025-09-03T20:13:54.324+0200] {processor.py:755} WARNING - No viable dags retrieved from /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py
[2025-09-03T20:13:54.343+0200] {processor.py:175} INFO - Processing /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py took 0.027 seconds
[2025-09-03T20:14:36.890+0200] {processor.py:153} INFO - Started process (PID=4803) to work on /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py
[2025-09-03T20:14:36.891+0200] {processor.py:743} INFO - Processing file /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py for tasks to queue
[2025-09-03T20:14:36.892+0200] {logging_mixin.py:137} INFO - [2025-09-03T20:14:36.892+0200] {dagbag.py:532} INFO - Filling up the DagBag from /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py
[2025-09-03T20:14:36.894+0200] {logging_mixin.py:137} INFO - [2025-09-03T20:14:36.894+0200] {dagbag.py:341} ERROR - Failed to import: /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py
Traceback (most recent call last):
  File "/home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py", line 24, in <module>
    from pandas.tseries.holiday import USFederalHolidayCalendar
ModuleNotFoundError: No module named 'pandas'
[2025-09-03T20:14:36.895+0200] {processor.py:755} WARNING - No viable dags retrieved from /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py
[2025-09-03T20:14:36.916+0200] {processor.py:175} INFO - Processing /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py took 0.029 seconds
[2025-09-03T20:15:24.675+0200] {processor.py:153} INFO - Started process (PID=4845) to work on /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py
[2025-09-03T20:15:24.677+0200] {processor.py:743} INFO - Processing file /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py for tasks to queue
[2025-09-03T20:15:24.677+0200] {logging_mixin.py:137} INFO - [2025-09-03T20:15:24.677+0200] {dagbag.py:532} INFO - Filling up the DagBag from /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py
[2025-09-03T20:15:24.680+0200] {logging_mixin.py:137} INFO - [2025-09-03T20:15:24.679+0200] {dagbag.py:341} ERROR - Failed to import: /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py
Traceback (most recent call last):
  File "/home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py", line 24, in <module>
    from pandas.tseries.holiday import USFederalHolidayCalendar
ModuleNotFoundError: No module named 'pandas'
[2025-09-03T20:15:24.680+0200] {processor.py:755} WARNING - No viable dags retrieved from /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py
[2025-09-03T20:15:24.697+0200] {processor.py:175} INFO - Processing /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py took 0.025 seconds
[2025-09-03T20:16:09.981+0200] {processor.py:153} INFO - Started process (PID=4887) to work on /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py
[2025-09-03T20:16:09.983+0200] {processor.py:743} INFO - Processing file /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py for tasks to queue
[2025-09-03T20:16:09.983+0200] {logging_mixin.py:137} INFO - [2025-09-03T20:16:09.983+0200] {dagbag.py:532} INFO - Filling up the DagBag from /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py
[2025-09-03T20:16:09.986+0200] {logging_mixin.py:137} INFO - [2025-09-03T20:16:09.985+0200] {dagbag.py:341} ERROR - Failed to import: /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py
Traceback (most recent call last):
  File "/home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py", line 24, in <module>
    from pandas.tseries.holiday import USFederalHolidayCalendar
ModuleNotFoundError: No module named 'pandas'
[2025-09-03T20:16:09.986+0200] {processor.py:755} WARNING - No viable dags retrieved from /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py
[2025-09-03T20:16:10.004+0200] {processor.py:175} INFO - Processing /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py took 0.026 seconds
[2025-09-03T20:16:54.414+0200] {processor.py:153} INFO - Started process (PID=4929) to work on /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py
[2025-09-03T20:16:54.416+0200] {processor.py:743} INFO - Processing file /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py for tasks to queue
[2025-09-03T20:16:54.417+0200] {logging_mixin.py:137} INFO - [2025-09-03T20:16:54.416+0200] {dagbag.py:532} INFO - Filling up the DagBag from /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py
[2025-09-03T20:16:54.419+0200] {logging_mixin.py:137} INFO - [2025-09-03T20:16:54.418+0200] {dagbag.py:341} ERROR - Failed to import: /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py
Traceback (most recent call last):
  File "/home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py", line 24, in <module>
    from pandas.tseries.holiday import USFederalHolidayCalendar
ModuleNotFoundError: No module named 'pandas'
[2025-09-03T20:16:54.419+0200] {processor.py:755} WARNING - No viable dags retrieved from /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py
[2025-09-03T20:16:54.439+0200] {processor.py:175} INFO - Processing /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py took 0.028 seconds
[2025-09-03T20:17:43.587+0200] {processor.py:153} INFO - Started process (PID=4974) to work on /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py
[2025-09-03T20:17:43.588+0200] {processor.py:743} INFO - Processing file /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py for tasks to queue
[2025-09-03T20:17:43.589+0200] {logging_mixin.py:137} INFO - [2025-09-03T20:17:43.589+0200] {dagbag.py:532} INFO - Filling up the DagBag from /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py
[2025-09-03T20:17:43.593+0200] {logging_mixin.py:137} INFO - [2025-09-03T20:17:43.592+0200] {dagbag.py:341} ERROR - Failed to import: /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py
Traceback (most recent call last):
  File "/home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py", line 24, in <module>
    from pandas.tseries.holiday import USFederalHolidayCalendar
ModuleNotFoundError: No module named 'pandas'
[2025-09-03T20:17:43.594+0200] {processor.py:755} WARNING - No viable dags retrieved from /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py
[2025-09-03T20:17:43.617+0200] {processor.py:175} INFO - Processing /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py took 0.033 seconds
[2025-09-03T20:18:28.110+0200] {processor.py:153} INFO - Started process (PID=5017) to work on /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py
[2025-09-03T20:18:28.111+0200] {processor.py:743} INFO - Processing file /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py for tasks to queue
[2025-09-03T20:18:28.112+0200] {logging_mixin.py:137} INFO - [2025-09-03T20:18:28.112+0200] {dagbag.py:532} INFO - Filling up the DagBag from /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py
[2025-09-03T20:18:28.116+0200] {logging_mixin.py:137} INFO - [2025-09-03T20:18:28.115+0200] {dagbag.py:341} ERROR - Failed to import: /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py
Traceback (most recent call last):
  File "/home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py", line 24, in <module>
    from pandas.tseries.holiday import USFederalHolidayCalendar
ModuleNotFoundError: No module named 'pandas'
[2025-09-03T20:18:28.117+0200] {processor.py:755} WARNING - No viable dags retrieved from /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py
[2025-09-03T20:18:28.138+0200] {processor.py:175} INFO - Processing /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py took 0.031 seconds
[2025-09-03T20:19:15.721+0200] {processor.py:153} INFO - Started process (PID=5059) to work on /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py
[2025-09-03T20:19:15.723+0200] {processor.py:743} INFO - Processing file /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py for tasks to queue
[2025-09-03T20:19:15.723+0200] {logging_mixin.py:137} INFO - [2025-09-03T20:19:15.723+0200] {dagbag.py:532} INFO - Filling up the DagBag from /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py
[2025-09-03T20:19:15.726+0200] {logging_mixin.py:137} INFO - [2025-09-03T20:19:15.725+0200] {dagbag.py:341} ERROR - Failed to import: /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py
Traceback (most recent call last):
  File "/home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py", line 24, in <module>
    from pandas.tseries.holiday import USFederalHolidayCalendar
ModuleNotFoundError: No module named 'pandas'
[2025-09-03T20:19:15.726+0200] {processor.py:755} WARNING - No viable dags retrieved from /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py
[2025-09-03T20:19:15.748+0200] {processor.py:175} INFO - Processing /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py took 0.030 seconds
[2025-09-03T20:20:08.278+0200] {processor.py:153} INFO - Started process (PID=5101) to work on /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py
[2025-09-03T20:20:08.279+0200] {processor.py:743} INFO - Processing file /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py for tasks to queue
[2025-09-03T20:20:08.280+0200] {logging_mixin.py:137} INFO - [2025-09-03T20:20:08.280+0200] {dagbag.py:532} INFO - Filling up the DagBag from /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py
[2025-09-03T20:20:08.283+0200] {logging_mixin.py:137} INFO - [2025-09-03T20:20:08.282+0200] {dagbag.py:341} ERROR - Failed to import: /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py
Traceback (most recent call last):
  File "/home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py", line 24, in <module>
    from pandas.tseries.holiday import USFederalHolidayCalendar
ModuleNotFoundError: No module named 'pandas'
[2025-09-03T20:20:08.283+0200] {processor.py:755} WARNING - No viable dags retrieved from /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py
[2025-09-03T20:20:08.305+0200] {processor.py:175} INFO - Processing /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py took 0.031 seconds
[2025-09-03T20:20:58.466+0200] {processor.py:153} INFO - Started process (PID=5143) to work on /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py
[2025-09-03T20:20:58.468+0200] {processor.py:743} INFO - Processing file /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py for tasks to queue
[2025-09-03T20:20:58.468+0200] {logging_mixin.py:137} INFO - [2025-09-03T20:20:58.468+0200] {dagbag.py:532} INFO - Filling up the DagBag from /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py
[2025-09-03T20:20:58.472+0200] {logging_mixin.py:137} INFO - [2025-09-03T20:20:58.470+0200] {dagbag.py:341} ERROR - Failed to import: /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py
Traceback (most recent call last):
  File "/home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py", line 24, in <module>
    from pandas.tseries.holiday import USFederalHolidayCalendar
ModuleNotFoundError: No module named 'pandas'
[2025-09-03T20:20:58.472+0200] {processor.py:755} WARNING - No viable dags retrieved from /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py
[2025-09-03T20:20:58.495+0200] {processor.py:175} INFO - Processing /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py took 0.032 seconds
[2025-09-03T20:21:47.533+0200] {processor.py:153} INFO - Started process (PID=5185) to work on /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py
[2025-09-03T20:21:47.534+0200] {processor.py:743} INFO - Processing file /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py for tasks to queue
[2025-09-03T20:21:47.534+0200] {logging_mixin.py:137} INFO - [2025-09-03T20:21:47.534+0200] {dagbag.py:532} INFO - Filling up the DagBag from /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py
[2025-09-03T20:21:47.537+0200] {logging_mixin.py:137} INFO - [2025-09-03T20:21:47.536+0200] {dagbag.py:341} ERROR - Failed to import: /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py
Traceback (most recent call last):
  File "/home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py", line 24, in <module>
    from pandas.tseries.holiday import USFederalHolidayCalendar
ModuleNotFoundError: No module named 'pandas'
[2025-09-03T20:21:47.537+0200] {processor.py:755} WARNING - No viable dags retrieved from /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py
[2025-09-03T20:21:47.559+0200] {processor.py:175} INFO - Processing /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py took 0.030 seconds
[2025-09-03T20:22:40.787+0200] {processor.py:153} INFO - Started process (PID=5227) to work on /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py
[2025-09-03T20:22:40.788+0200] {processor.py:743} INFO - Processing file /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py for tasks to queue
[2025-09-03T20:22:40.789+0200] {logging_mixin.py:137} INFO - [2025-09-03T20:22:40.789+0200] {dagbag.py:532} INFO - Filling up the DagBag from /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py
[2025-09-03T20:22:40.791+0200] {logging_mixin.py:137} INFO - [2025-09-03T20:22:40.790+0200] {dagbag.py:341} ERROR - Failed to import: /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py
Traceback (most recent call last):
  File "/home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py", line 24, in <module>
    from pandas.tseries.holiday import USFederalHolidayCalendar
ModuleNotFoundError: No module named 'pandas'
[2025-09-03T20:22:40.791+0200] {processor.py:755} WARNING - No viable dags retrieved from /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py
[2025-09-03T20:22:40.811+0200] {processor.py:175} INFO - Processing /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py took 0.027 seconds
[2025-09-03T20:23:28.987+0200] {processor.py:153} INFO - Started process (PID=5269) to work on /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py
[2025-09-03T20:23:28.989+0200] {processor.py:743} INFO - Processing file /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py for tasks to queue
[2025-09-03T20:23:28.989+0200] {logging_mixin.py:137} INFO - [2025-09-03T20:23:28.989+0200] {dagbag.py:532} INFO - Filling up the DagBag from /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py
[2025-09-03T20:23:28.992+0200] {logging_mixin.py:137} INFO - [2025-09-03T20:23:28.991+0200] {dagbag.py:341} ERROR - Failed to import: /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py
Traceback (most recent call last):
  File "/home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py", line 24, in <module>
    from pandas.tseries.holiday import USFederalHolidayCalendar
ModuleNotFoundError: No module named 'pandas'
[2025-09-03T20:23:28.993+0200] {processor.py:755} WARNING - No viable dags retrieved from /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py
[2025-09-03T20:23:29.017+0200] {processor.py:175} INFO - Processing /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py took 0.034 seconds
[2025-09-03T20:24:18.238+0200] {processor.py:153} INFO - Started process (PID=5312) to work on /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py
[2025-09-03T20:24:18.240+0200] {processor.py:743} INFO - Processing file /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py for tasks to queue
[2025-09-03T20:24:18.242+0200] {logging_mixin.py:137} INFO - [2025-09-03T20:24:18.241+0200] {dagbag.py:532} INFO - Filling up the DagBag from /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py
[2025-09-03T20:24:18.247+0200] {logging_mixin.py:137} INFO - [2025-09-03T20:24:18.245+0200] {dagbag.py:341} ERROR - Failed to import: /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py
Traceback (most recent call last):
  File "/home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py", line 24, in <module>
    from pandas.tseries.holiday import USFederalHolidayCalendar
ModuleNotFoundError: No module named 'pandas'
[2025-09-03T20:24:18.248+0200] {processor.py:755} WARNING - No viable dags retrieved from /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py
[2025-09-03T20:24:18.283+0200] {processor.py:175} INFO - Processing /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py took 0.050 seconds
[2025-09-03T20:25:04.678+0200] {processor.py:153} INFO - Started process (PID=5354) to work on /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py
[2025-09-03T20:25:04.679+0200] {processor.py:743} INFO - Processing file /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py for tasks to queue
[2025-09-03T20:25:04.680+0200] {logging_mixin.py:137} INFO - [2025-09-03T20:25:04.680+0200] {dagbag.py:532} INFO - Filling up the DagBag from /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py
[2025-09-03T20:25:04.683+0200] {logging_mixin.py:137} INFO - [2025-09-03T20:25:04.682+0200] {dagbag.py:341} ERROR - Failed to import: /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py
Traceback (most recent call last):
  File "/home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py", line 24, in <module>
    from pandas.tseries.holiday import USFederalHolidayCalendar
ModuleNotFoundError: No module named 'pandas'
[2025-09-03T20:25:04.683+0200] {processor.py:755} WARNING - No viable dags retrieved from /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py
[2025-09-03T20:25:04.703+0200] {processor.py:175} INFO - Processing /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py took 0.029 seconds
[2025-09-03T20:25:46.037+0200] {processor.py:153} INFO - Started process (PID=5396) to work on /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py
[2025-09-03T20:25:46.039+0200] {processor.py:743} INFO - Processing file /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py for tasks to queue
[2025-09-03T20:25:46.039+0200] {logging_mixin.py:137} INFO - [2025-09-03T20:25:46.039+0200] {dagbag.py:532} INFO - Filling up the DagBag from /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py
[2025-09-03T20:25:46.042+0200] {logging_mixin.py:137} INFO - [2025-09-03T20:25:46.041+0200] {dagbag.py:341} ERROR - Failed to import: /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py
Traceback (most recent call last):
  File "/home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py", line 24, in <module>
    from pandas.tseries.holiday import USFederalHolidayCalendar
ModuleNotFoundError: No module named 'pandas'
[2025-09-03T20:25:46.042+0200] {processor.py:755} WARNING - No viable dags retrieved from /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py
[2025-09-03T20:25:46.061+0200] {processor.py:175} INFO - Processing /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py took 0.027 seconds
[2025-09-03T20:26:32.228+0200] {processor.py:153} INFO - Started process (PID=5438) to work on /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py
[2025-09-03T20:26:32.229+0200] {processor.py:743} INFO - Processing file /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py for tasks to queue
[2025-09-03T20:26:32.230+0200] {logging_mixin.py:137} INFO - [2025-09-03T20:26:32.230+0200] {dagbag.py:532} INFO - Filling up the DagBag from /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py
[2025-09-03T20:26:32.233+0200] {logging_mixin.py:137} INFO - [2025-09-03T20:26:32.232+0200] {dagbag.py:341} ERROR - Failed to import: /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py
Traceback (most recent call last):
  File "/home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py", line 24, in <module>
    from pandas.tseries.holiday import USFederalHolidayCalendar
ModuleNotFoundError: No module named 'pandas'
[2025-09-03T20:26:32.233+0200] {processor.py:755} WARNING - No viable dags retrieved from /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py
[2025-09-03T20:26:32.256+0200] {processor.py:175} INFO - Processing /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py took 0.031 seconds
[2025-09-03T20:27:21.707+0200] {processor.py:153} INFO - Started process (PID=5480) to work on /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py
[2025-09-03T20:27:21.708+0200] {processor.py:743} INFO - Processing file /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py for tasks to queue
[2025-09-03T20:27:21.708+0200] {logging_mixin.py:137} INFO - [2025-09-03T20:27:21.708+0200] {dagbag.py:532} INFO - Filling up the DagBag from /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py
[2025-09-03T20:27:21.711+0200] {logging_mixin.py:137} INFO - [2025-09-03T20:27:21.710+0200] {dagbag.py:341} ERROR - Failed to import: /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py
Traceback (most recent call last):
  File "/home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py", line 24, in <module>
    from pandas.tseries.holiday import USFederalHolidayCalendar
ModuleNotFoundError: No module named 'pandas'
[2025-09-03T20:27:21.711+0200] {processor.py:755} WARNING - No viable dags retrieved from /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py
[2025-09-03T20:27:21.734+0200] {processor.py:175} INFO - Processing /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py took 0.030 seconds
[2025-09-03T20:28:08.108+0200] {processor.py:153} INFO - Started process (PID=5522) to work on /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py
[2025-09-03T20:28:08.110+0200] {processor.py:743} INFO - Processing file /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py for tasks to queue
[2025-09-03T20:28:08.111+0200] {logging_mixin.py:137} INFO - [2025-09-03T20:28:08.110+0200] {dagbag.py:532} INFO - Filling up the DagBag from /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py
[2025-09-03T20:28:08.116+0200] {logging_mixin.py:137} INFO - [2025-09-03T20:28:08.115+0200] {dagbag.py:341} ERROR - Failed to import: /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py
Traceback (most recent call last):
  File "/home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py", line 24, in <module>
    from pandas.tseries.holiday import USFederalHolidayCalendar
ModuleNotFoundError: No module named 'pandas'
[2025-09-03T20:28:08.116+0200] {processor.py:755} WARNING - No viable dags retrieved from /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py
[2025-09-03T20:28:08.140+0200] {processor.py:175} INFO - Processing /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py took 0.036 seconds
[2025-09-03T20:28:53.966+0200] {processor.py:153} INFO - Started process (PID=5564) to work on /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py
[2025-09-03T20:28:53.968+0200] {processor.py:743} INFO - Processing file /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py for tasks to queue
[2025-09-03T20:28:53.968+0200] {logging_mixin.py:137} INFO - [2025-09-03T20:28:53.968+0200] {dagbag.py:532} INFO - Filling up the DagBag from /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py
[2025-09-03T20:28:53.972+0200] {logging_mixin.py:137} INFO - [2025-09-03T20:28:53.970+0200] {dagbag.py:341} ERROR - Failed to import: /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py
Traceback (most recent call last):
  File "/home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py", line 24, in <module>
    from pandas.tseries.holiday import USFederalHolidayCalendar
ModuleNotFoundError: No module named 'pandas'
[2025-09-03T20:28:53.972+0200] {processor.py:755} WARNING - No viable dags retrieved from /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py
[2025-09-03T20:28:53.993+0200] {processor.py:175} INFO - Processing /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py took 0.030 seconds
[2025-09-03T20:29:43.743+0200] {processor.py:153} INFO - Started process (PID=5607) to work on /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py
[2025-09-03T20:29:43.745+0200] {processor.py:743} INFO - Processing file /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py for tasks to queue
[2025-09-03T20:29:43.747+0200] {logging_mixin.py:137} INFO - [2025-09-03T20:29:43.747+0200] {dagbag.py:532} INFO - Filling up the DagBag from /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py
[2025-09-03T20:29:43.751+0200] {logging_mixin.py:137} INFO - [2025-09-03T20:29:43.750+0200] {dagbag.py:341} ERROR - Failed to import: /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py
Traceback (most recent call last):
  File "/home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py", line 24, in <module>
    from pandas.tseries.holiday import USFederalHolidayCalendar
ModuleNotFoundError: No module named 'pandas'
[2025-09-03T20:29:43.752+0200] {processor.py:755} WARNING - No viable dags retrieved from /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py
[2025-09-03T20:29:43.779+0200] {processor.py:175} INFO - Processing /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py took 0.040 seconds
[2025-09-03T20:30:28.615+0200] {processor.py:153} INFO - Started process (PID=5649) to work on /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py
[2025-09-03T20:30:28.616+0200] {processor.py:743} INFO - Processing file /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py for tasks to queue
[2025-09-03T20:30:28.617+0200] {logging_mixin.py:137} INFO - [2025-09-03T20:30:28.617+0200] {dagbag.py:532} INFO - Filling up the DagBag from /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py
[2025-09-03T20:30:28.620+0200] {logging_mixin.py:137} INFO - [2025-09-03T20:30:28.619+0200] {dagbag.py:341} ERROR - Failed to import: /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py
Traceback (most recent call last):
  File "/home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py", line 24, in <module>
    from pandas.tseries.holiday import USFederalHolidayCalendar
ModuleNotFoundError: No module named 'pandas'
[2025-09-03T20:30:28.620+0200] {processor.py:755} WARNING - No viable dags retrieved from /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py
[2025-09-03T20:30:28.643+0200] {processor.py:175} INFO - Processing /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py took 0.032 seconds
[2025-09-03T20:31:12.280+0200] {processor.py:153} INFO - Started process (PID=5691) to work on /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py
[2025-09-03T20:31:12.281+0200] {processor.py:743} INFO - Processing file /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py for tasks to queue
[2025-09-03T20:31:12.282+0200] {logging_mixin.py:137} INFO - [2025-09-03T20:31:12.282+0200] {dagbag.py:532} INFO - Filling up the DagBag from /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py
[2025-09-03T20:31:12.284+0200] {logging_mixin.py:137} INFO - [2025-09-03T20:31:12.283+0200] {dagbag.py:341} ERROR - Failed to import: /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py
Traceback (most recent call last):
  File "/home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py", line 24, in <module>
    from pandas.tseries.holiday import USFederalHolidayCalendar
ModuleNotFoundError: No module named 'pandas'
[2025-09-03T20:31:12.285+0200] {processor.py:755} WARNING - No viable dags retrieved from /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py
[2025-09-03T20:31:12.307+0200] {processor.py:175} INFO - Processing /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py took 0.030 seconds
[2025-09-03T20:32:01.993+0200] {processor.py:153} INFO - Started process (PID=5733) to work on /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py
[2025-09-03T20:32:01.994+0200] {processor.py:743} INFO - Processing file /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py for tasks to queue
[2025-09-03T20:32:01.995+0200] {logging_mixin.py:137} INFO - [2025-09-03T20:32:01.995+0200] {dagbag.py:532} INFO - Filling up the DagBag from /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py
[2025-09-03T20:32:01.998+0200] {logging_mixin.py:137} INFO - [2025-09-03T20:32:01.997+0200] {dagbag.py:341} ERROR - Failed to import: /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py
Traceback (most recent call last):
  File "/home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py", line 24, in <module>
    from pandas.tseries.holiday import USFederalHolidayCalendar
ModuleNotFoundError: No module named 'pandas'
[2025-09-03T20:32:01.999+0200] {processor.py:755} WARNING - No viable dags retrieved from /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py
[2025-09-03T20:32:02.020+0200] {processor.py:175} INFO - Processing /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py took 0.031 seconds
[2025-09-03T20:32:45.625+0200] {processor.py:153} INFO - Started process (PID=5775) to work on /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py
[2025-09-03T20:32:45.628+0200] {processor.py:743} INFO - Processing file /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py for tasks to queue
[2025-09-03T20:32:45.628+0200] {logging_mixin.py:137} INFO - [2025-09-03T20:32:45.628+0200] {dagbag.py:532} INFO - Filling up the DagBag from /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py
[2025-09-03T20:32:45.631+0200] {logging_mixin.py:137} INFO - [2025-09-03T20:32:45.630+0200] {dagbag.py:341} ERROR - Failed to import: /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py
Traceback (most recent call last):
  File "/home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py", line 24, in <module>
    from pandas.tseries.holiday import USFederalHolidayCalendar
ModuleNotFoundError: No module named 'pandas'
[2025-09-03T20:32:45.631+0200] {processor.py:755} WARNING - No viable dags retrieved from /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py
[2025-09-03T20:32:45.650+0200] {processor.py:175} INFO - Processing /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py took 0.027 seconds
[2025-09-03T20:33:31.435+0200] {processor.py:153} INFO - Started process (PID=5817) to work on /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py
[2025-09-03T20:33:31.436+0200] {processor.py:743} INFO - Processing file /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py for tasks to queue
[2025-09-03T20:33:31.437+0200] {logging_mixin.py:137} INFO - [2025-09-03T20:33:31.436+0200] {dagbag.py:532} INFO - Filling up the DagBag from /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py
[2025-09-03T20:33:31.440+0200] {logging_mixin.py:137} INFO - [2025-09-03T20:33:31.439+0200] {dagbag.py:341} ERROR - Failed to import: /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py
Traceback (most recent call last):
  File "/home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py", line 24, in <module>
    from pandas.tseries.holiday import USFederalHolidayCalendar
ModuleNotFoundError: No module named 'pandas'
[2025-09-03T20:33:31.440+0200] {processor.py:755} WARNING - No viable dags retrieved from /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py
[2025-09-03T20:33:31.458+0200] {processor.py:175} INFO - Processing /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py took 0.026 seconds
[2025-09-03T20:34:16.846+0200] {processor.py:153} INFO - Started process (PID=5859) to work on /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py
[2025-09-03T20:34:16.847+0200] {processor.py:743} INFO - Processing file /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py for tasks to queue
[2025-09-03T20:34:16.848+0200] {logging_mixin.py:137} INFO - [2025-09-03T20:34:16.848+0200] {dagbag.py:532} INFO - Filling up the DagBag from /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py
[2025-09-03T20:34:16.850+0200] {logging_mixin.py:137} INFO - [2025-09-03T20:34:16.850+0200] {dagbag.py:341} ERROR - Failed to import: /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py
Traceback (most recent call last):
  File "/home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py", line 24, in <module>
    from pandas.tseries.holiday import USFederalHolidayCalendar
ModuleNotFoundError: No module named 'pandas'
[2025-09-03T20:34:16.851+0200] {processor.py:755} WARNING - No viable dags retrieved from /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py
[2025-09-03T20:34:16.870+0200] {processor.py:175} INFO - Processing /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py took 0.027 seconds
[2025-09-03T20:35:04.533+0200] {processor.py:153} INFO - Started process (PID=5902) to work on /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py
[2025-09-03T20:35:04.534+0200] {processor.py:743} INFO - Processing file /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py for tasks to queue
[2025-09-03T20:35:04.535+0200] {logging_mixin.py:137} INFO - [2025-09-03T20:35:04.535+0200] {dagbag.py:532} INFO - Filling up the DagBag from /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py
[2025-09-03T20:35:04.537+0200] {logging_mixin.py:137} INFO - [2025-09-03T20:35:04.536+0200] {dagbag.py:341} ERROR - Failed to import: /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py
Traceback (most recent call last):
  File "/home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py", line 24, in <module>
    from pandas.tseries.holiday import USFederalHolidayCalendar
ModuleNotFoundError: No module named 'pandas'
[2025-09-03T20:35:04.537+0200] {processor.py:755} WARNING - No viable dags retrieved from /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py
[2025-09-03T20:35:04.557+0200] {processor.py:175} INFO - Processing /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py took 0.027 seconds
[2025-09-03T20:35:49.041+0200] {processor.py:153} INFO - Started process (PID=5944) to work on /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py
[2025-09-03T20:35:49.043+0200] {processor.py:743} INFO - Processing file /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py for tasks to queue
[2025-09-03T20:35:49.043+0200] {logging_mixin.py:137} INFO - [2025-09-03T20:35:49.043+0200] {dagbag.py:532} INFO - Filling up the DagBag from /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py
[2025-09-03T20:35:49.046+0200] {logging_mixin.py:137} INFO - [2025-09-03T20:35:49.045+0200] {dagbag.py:341} ERROR - Failed to import: /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py
Traceback (most recent call last):
  File "/home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py", line 24, in <module>
    from pandas.tseries.holiday import USFederalHolidayCalendar
ModuleNotFoundError: No module named 'pandas'
[2025-09-03T20:35:49.046+0200] {processor.py:755} WARNING - No viable dags retrieved from /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py
[2025-09-03T20:35:49.066+0200] {processor.py:175} INFO - Processing /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py took 0.027 seconds
[2025-09-03T20:36:35.495+0200] {processor.py:153} INFO - Started process (PID=5986) to work on /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py
[2025-09-03T20:36:35.497+0200] {processor.py:743} INFO - Processing file /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py for tasks to queue
[2025-09-03T20:36:35.498+0200] {logging_mixin.py:137} INFO - [2025-09-03T20:36:35.498+0200] {dagbag.py:532} INFO - Filling up the DagBag from /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py
[2025-09-03T20:36:35.501+0200] {logging_mixin.py:137} INFO - [2025-09-03T20:36:35.500+0200] {dagbag.py:341} ERROR - Failed to import: /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py
Traceback (most recent call last):
  File "/home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py", line 24, in <module>
    from pandas.tseries.holiday import USFederalHolidayCalendar
ModuleNotFoundError: No module named 'pandas'
[2025-09-03T20:36:35.501+0200] {processor.py:755} WARNING - No viable dags retrieved from /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py
[2025-09-03T20:36:35.521+0200] {processor.py:175} INFO - Processing /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py took 0.029 seconds
