[2025-09-03T19:42:49.600+0200] {processor.py:153} INFO - Started process (PID=3110) to work on /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-09-03T19:42:49.601+0200] {processor.py:743} INFO - Processing file /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-09-03T19:42:49.602+0200] {logging_mixin.py:137} INFO - [2025-09-03T19:42:49.602+0200] {dagbag.py:532} INFO - Filling up the DagBag from /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-09-03T19:42:49.616+0200] {logging_mixin.py:137} INFO - [2025-09-03T19:42:49.616+0200] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-09-03T19:42:49.617+0200] {logging_mixin.py:137} INFO - [2025-09-03T19:42:49.617+0200] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-09-03T19:42:49.617+0200] {processor.py:755} WARNING - No viable dags retrieved from /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-09-03T19:42:49.626+0200] {processor.py:175} INFO - Processing /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.029 seconds
[2025-09-03T19:43:36.950+0200] {processor.py:153} INFO - Started process (PID=3152) to work on /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-09-03T19:43:36.952+0200] {processor.py:743} INFO - Processing file /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-09-03T19:43:36.953+0200] {logging_mixin.py:137} INFO - [2025-09-03T19:43:36.953+0200] {dagbag.py:532} INFO - Filling up the DagBag from /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-09-03T19:43:36.970+0200] {logging_mixin.py:137} INFO - [2025-09-03T19:43:36.969+0200] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-09-03T19:43:36.970+0200] {logging_mixin.py:137} INFO - [2025-09-03T19:43:36.970+0200] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-09-03T19:43:36.970+0200] {processor.py:755} WARNING - No viable dags retrieved from /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-09-03T19:43:36.979+0200] {processor.py:175} INFO - Processing /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.032 seconds
[2025-09-03T19:44:26.923+0200] {processor.py:153} INFO - Started process (PID=3194) to work on /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-09-03T19:44:26.925+0200] {processor.py:743} INFO - Processing file /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-09-03T19:44:26.925+0200] {logging_mixin.py:137} INFO - [2025-09-03T19:44:26.925+0200] {dagbag.py:532} INFO - Filling up the DagBag from /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-09-03T19:44:26.939+0200] {logging_mixin.py:137} INFO - [2025-09-03T19:44:26.938+0200] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-09-03T19:44:26.939+0200] {logging_mixin.py:137} INFO - [2025-09-03T19:44:26.939+0200] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-09-03T19:44:26.939+0200] {processor.py:755} WARNING - No viable dags retrieved from /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-09-03T19:44:26.949+0200] {processor.py:175} INFO - Processing /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.028 seconds
[2025-09-03T19:45:14.885+0200] {processor.py:153} INFO - Started process (PID=3237) to work on /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-09-03T19:45:14.887+0200] {processor.py:743} INFO - Processing file /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-09-03T19:45:14.888+0200] {logging_mixin.py:137} INFO - [2025-09-03T19:45:14.887+0200] {dagbag.py:532} INFO - Filling up the DagBag from /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-09-03T19:45:14.901+0200] {logging_mixin.py:137} INFO - [2025-09-03T19:45:14.901+0200] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-09-03T19:45:14.901+0200] {logging_mixin.py:137} INFO - [2025-09-03T19:45:14.901+0200] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-09-03T19:45:14.902+0200] {processor.py:755} WARNING - No viable dags retrieved from /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-09-03T19:45:14.910+0200] {processor.py:175} INFO - Processing /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.028 seconds
[2025-09-03T19:46:03.801+0200] {processor.py:153} INFO - Started process (PID=3307) to work on /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-09-03T19:46:03.804+0200] {processor.py:743} INFO - Processing file /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-09-03T19:46:03.804+0200] {logging_mixin.py:137} INFO - [2025-09-03T19:46:03.804+0200] {dagbag.py:532} INFO - Filling up the DagBag from /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-09-03T19:46:03.825+0200] {logging_mixin.py:137} INFO - [2025-09-03T19:46:03.824+0200] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-09-03T19:46:03.825+0200] {logging_mixin.py:137} INFO - [2025-09-03T19:46:03.825+0200] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-09-03T19:46:03.825+0200] {processor.py:755} WARNING - No viable dags retrieved from /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-09-03T19:46:03.838+0200] {processor.py:175} INFO - Processing /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.042 seconds
[2025-09-03T19:46:49.135+0200] {processor.py:153} INFO - Started process (PID=3355) to work on /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-09-03T19:46:49.137+0200] {processor.py:743} INFO - Processing file /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-09-03T19:46:49.137+0200] {logging_mixin.py:137} INFO - [2025-09-03T19:46:49.137+0200] {dagbag.py:532} INFO - Filling up the DagBag from /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-09-03T19:46:49.151+0200] {logging_mixin.py:137} INFO - [2025-09-03T19:46:49.150+0200] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-09-03T19:46:49.151+0200] {logging_mixin.py:137} INFO - [2025-09-03T19:46:49.151+0200] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-09-03T19:46:49.151+0200] {processor.py:755} WARNING - No viable dags retrieved from /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-09-03T19:46:49.161+0200] {processor.py:175} INFO - Processing /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.029 seconds
[2025-09-03T19:47:35.611+0200] {processor.py:153} INFO - Started process (PID=3405) to work on /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-09-03T19:47:35.613+0200] {processor.py:743} INFO - Processing file /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-09-03T19:47:35.614+0200] {logging_mixin.py:137} INFO - [2025-09-03T19:47:35.614+0200] {dagbag.py:532} INFO - Filling up the DagBag from /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-09-03T19:47:35.630+0200] {logging_mixin.py:137} INFO - [2025-09-03T19:47:35.629+0200] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-09-03T19:47:35.630+0200] {logging_mixin.py:137} INFO - [2025-09-03T19:47:35.630+0200] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-09-03T19:47:35.630+0200] {processor.py:755} WARNING - No viable dags retrieved from /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-09-03T19:47:35.641+0200] {processor.py:175} INFO - Processing /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.033 seconds
[2025-09-03T19:48:19.693+0200] {processor.py:153} INFO - Started process (PID=3447) to work on /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-09-03T19:48:19.695+0200] {processor.py:743} INFO - Processing file /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-09-03T19:48:19.696+0200] {logging_mixin.py:137} INFO - [2025-09-03T19:48:19.696+0200] {dagbag.py:532} INFO - Filling up the DagBag from /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-09-03T19:48:19.712+0200] {logging_mixin.py:137} INFO - [2025-09-03T19:48:19.711+0200] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-09-03T19:48:19.712+0200] {logging_mixin.py:137} INFO - [2025-09-03T19:48:19.712+0200] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-09-03T19:48:19.712+0200] {processor.py:755} WARNING - No viable dags retrieved from /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-09-03T19:48:19.722+0200] {processor.py:175} INFO - Processing /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.033 seconds
[2025-09-03T19:49:12.614+0200] {processor.py:153} INFO - Started process (PID=3489) to work on /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-09-03T19:49:12.616+0200] {processor.py:743} INFO - Processing file /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-09-03T19:49:12.617+0200] {logging_mixin.py:137} INFO - [2025-09-03T19:49:12.617+0200] {dagbag.py:532} INFO - Filling up the DagBag from /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-09-03T19:49:12.651+0200] {logging_mixin.py:137} INFO - [2025-09-03T19:49:12.649+0200] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-09-03T19:49:12.652+0200] {logging_mixin.py:137} INFO - [2025-09-03T19:49:12.652+0200] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-09-03T19:49:12.652+0200] {processor.py:755} WARNING - No viable dags retrieved from /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-09-03T19:49:12.674+0200] {processor.py:175} INFO - Processing /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.065 seconds
[2025-09-03T19:50:00.287+0200] {processor.py:153} INFO - Started process (PID=3540) to work on /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-09-03T19:50:00.291+0200] {processor.py:743} INFO - Processing file /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-09-03T19:50:00.293+0200] {logging_mixin.py:137} INFO - [2025-09-03T19:50:00.292+0200] {dagbag.py:532} INFO - Filling up the DagBag from /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-09-03T19:50:00.328+0200] {logging_mixin.py:137} INFO - [2025-09-03T19:50:00.326+0200] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-09-03T19:50:00.328+0200] {logging_mixin.py:137} INFO - [2025-09-03T19:50:00.328+0200] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-09-03T19:50:00.329+0200] {processor.py:755} WARNING - No viable dags retrieved from /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-09-03T19:50:00.345+0200] {processor.py:175} INFO - Processing /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.065 seconds
[2025-09-03T19:50:46.086+0200] {processor.py:153} INFO - Started process (PID=3583) to work on /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-09-03T19:50:46.088+0200] {processor.py:743} INFO - Processing file /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-09-03T19:50:46.089+0200] {logging_mixin.py:137} INFO - [2025-09-03T19:50:46.088+0200] {dagbag.py:532} INFO - Filling up the DagBag from /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-09-03T19:50:46.101+0200] {logging_mixin.py:137} INFO - [2025-09-03T19:50:46.101+0200] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-09-03T19:50:46.101+0200] {logging_mixin.py:137} INFO - [2025-09-03T19:50:46.101+0200] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-09-03T19:50:46.102+0200] {processor.py:755} WARNING - No viable dags retrieved from /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-09-03T19:50:46.110+0200] {processor.py:175} INFO - Processing /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.027 seconds
[2025-09-03T19:51:36.091+0200] {processor.py:153} INFO - Started process (PID=3638) to work on /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-09-03T19:51:36.093+0200] {processor.py:743} INFO - Processing file /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-09-03T19:51:36.094+0200] {logging_mixin.py:137} INFO - [2025-09-03T19:51:36.094+0200] {dagbag.py:532} INFO - Filling up the DagBag from /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-09-03T19:51:36.108+0200] {logging_mixin.py:137} INFO - [2025-09-03T19:51:36.107+0200] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-09-03T19:51:36.108+0200] {logging_mixin.py:137} INFO - [2025-09-03T19:51:36.108+0200] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-09-03T19:51:36.108+0200] {processor.py:755} WARNING - No viable dags retrieved from /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-09-03T19:51:36.116+0200] {processor.py:175} INFO - Processing /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.028 seconds
[2025-09-03T19:52:23.418+0200] {processor.py:153} INFO - Started process (PID=3687) to work on /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-09-03T19:52:23.420+0200] {processor.py:743} INFO - Processing file /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-09-03T19:52:23.420+0200] {logging_mixin.py:137} INFO - [2025-09-03T19:52:23.420+0200] {dagbag.py:532} INFO - Filling up the DagBag from /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-09-03T19:52:23.444+0200] {logging_mixin.py:137} INFO - [2025-09-03T19:52:23.443+0200] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-09-03T19:52:23.445+0200] {logging_mixin.py:137} INFO - [2025-09-03T19:52:23.444+0200] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-09-03T19:52:23.445+0200] {processor.py:755} WARNING - No viable dags retrieved from /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-09-03T19:52:23.458+0200] {processor.py:175} INFO - Processing /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.043 seconds
[2025-09-03T19:53:18.140+0200] {processor.py:153} INFO - Started process (PID=3729) to work on /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-09-03T19:53:18.142+0200] {processor.py:743} INFO - Processing file /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-09-03T19:53:18.142+0200] {logging_mixin.py:137} INFO - [2025-09-03T19:53:18.142+0200] {dagbag.py:532} INFO - Filling up the DagBag from /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-09-03T19:53:18.160+0200] {logging_mixin.py:137} INFO - [2025-09-03T19:53:18.159+0200] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-09-03T19:53:18.160+0200] {logging_mixin.py:137} INFO - [2025-09-03T19:53:18.160+0200] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-09-03T19:53:18.160+0200] {processor.py:755} WARNING - No viable dags retrieved from /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-09-03T19:53:18.170+0200] {processor.py:175} INFO - Processing /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.034 seconds
[2025-09-03T19:54:13.488+0200] {processor.py:153} INFO - Started process (PID=3780) to work on /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-09-03T19:54:13.489+0200] {processor.py:743} INFO - Processing file /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-09-03T19:54:13.490+0200] {logging_mixin.py:137} INFO - [2025-09-03T19:54:13.490+0200] {dagbag.py:532} INFO - Filling up the DagBag from /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-09-03T19:54:13.509+0200] {logging_mixin.py:137} INFO - [2025-09-03T19:54:13.508+0200] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-09-03T19:54:13.509+0200] {logging_mixin.py:137} INFO - [2025-09-03T19:54:13.509+0200] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-09-03T19:54:13.509+0200] {processor.py:755} WARNING - No viable dags retrieved from /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-09-03T19:54:13.520+0200] {processor.py:175} INFO - Processing /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.036 seconds
[2025-09-03T19:55:12.682+0200] {processor.py:153} INFO - Started process (PID=3832) to work on /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-09-03T19:55:12.689+0200] {processor.py:743} INFO - Processing file /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-09-03T19:55:12.691+0200] {logging_mixin.py:137} INFO - [2025-09-03T19:55:12.691+0200] {dagbag.py:532} INFO - Filling up the DagBag from /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-09-03T19:55:12.765+0200] {logging_mixin.py:137} INFO - [2025-09-03T19:55:12.759+0200] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-09-03T19:55:12.766+0200] {logging_mixin.py:137} INFO - [2025-09-03T19:55:12.765+0200] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-09-03T19:55:12.767+0200] {processor.py:755} WARNING - No viable dags retrieved from /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-09-03T19:55:12.805+0200] {processor.py:175} INFO - Processing /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.130 seconds
[2025-09-03T19:56:14.881+0200] {processor.py:153} INFO - Started process (PID=3888) to work on /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-09-03T19:56:14.882+0200] {processor.py:743} INFO - Processing file /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-09-03T19:56:14.884+0200] {logging_mixin.py:137} INFO - [2025-09-03T19:56:14.883+0200] {dagbag.py:532} INFO - Filling up the DagBag from /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-09-03T19:56:14.901+0200] {logging_mixin.py:137} INFO - [2025-09-03T19:56:14.901+0200] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-09-03T19:56:14.901+0200] {logging_mixin.py:137} INFO - [2025-09-03T19:56:14.901+0200] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-09-03T19:56:14.901+0200] {processor.py:755} WARNING - No viable dags retrieved from /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-09-03T19:56:15.028+0200] {processor.py:175} INFO - Processing /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.151 seconds
[2025-09-03T19:57:08.688+0200] {processor.py:153} INFO - Started process (PID=3933) to work on /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-09-03T19:57:08.690+0200] {processor.py:743} INFO - Processing file /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-09-03T19:57:08.691+0200] {logging_mixin.py:137} INFO - [2025-09-03T19:57:08.691+0200] {dagbag.py:532} INFO - Filling up the DagBag from /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-09-03T19:57:08.833+0200] {logging_mixin.py:137} INFO - [2025-09-03T19:57:08.832+0200] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-09-03T19:57:08.834+0200] {logging_mixin.py:137} INFO - [2025-09-03T19:57:08.833+0200] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-09-03T19:57:08.834+0200] {processor.py:755} WARNING - No viable dags retrieved from /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-09-03T19:57:08.843+0200] {processor.py:175} INFO - Processing /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.160 seconds
[2025-09-03T19:57:56.478+0200] {processor.py:153} INFO - Started process (PID=3977) to work on /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-09-03T19:57:56.480+0200] {processor.py:743} INFO - Processing file /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-09-03T19:57:56.481+0200] {logging_mixin.py:137} INFO - [2025-09-03T19:57:56.481+0200] {dagbag.py:532} INFO - Filling up the DagBag from /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-09-03T19:57:56.499+0200] {logging_mixin.py:137} INFO - [2025-09-03T19:57:56.498+0200] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-09-03T19:57:56.499+0200] {logging_mixin.py:137} INFO - [2025-09-03T19:57:56.499+0200] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-09-03T19:57:56.500+0200] {processor.py:755} WARNING - No viable dags retrieved from /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-09-03T19:57:56.513+0200] {processor.py:175} INFO - Processing /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.039 seconds
[2025-09-03T20:01:04.942+0200] {processor.py:153} INFO - Started process (PID=4048) to work on /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-09-03T20:01:04.944+0200] {processor.py:743} INFO - Processing file /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-09-03T20:01:04.945+0200] {logging_mixin.py:137} INFO - [2025-09-03T20:01:04.945+0200] {dagbag.py:532} INFO - Filling up the DagBag from /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-09-03T20:01:04.966+0200] {logging_mixin.py:137} INFO - [2025-09-03T20:01:04.965+0200] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-09-03T20:01:04.966+0200] {logging_mixin.py:137} INFO - [2025-09-03T20:01:04.966+0200] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-09-03T20:01:04.966+0200] {processor.py:755} WARNING - No viable dags retrieved from /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-09-03T20:01:04.980+0200] {processor.py:175} INFO - Processing /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.042 seconds
[2025-09-03T20:01:52.048+0200] {processor.py:153} INFO - Started process (PID=4095) to work on /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-09-03T20:01:52.050+0200] {processor.py:743} INFO - Processing file /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-09-03T20:01:52.051+0200] {logging_mixin.py:137} INFO - [2025-09-03T20:01:52.051+0200] {dagbag.py:532} INFO - Filling up the DagBag from /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-09-03T20:01:52.074+0200] {logging_mixin.py:137} INFO - [2025-09-03T20:01:52.073+0200] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-09-03T20:01:52.075+0200] {logging_mixin.py:137} INFO - [2025-09-03T20:01:52.075+0200] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-09-03T20:01:52.075+0200] {processor.py:755} WARNING - No viable dags retrieved from /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-09-03T20:01:52.088+0200] {processor.py:175} INFO - Processing /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.045 seconds
[2025-09-03T20:02:37.356+0200] {processor.py:153} INFO - Started process (PID=4137) to work on /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-09-03T20:02:37.358+0200] {processor.py:743} INFO - Processing file /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-09-03T20:02:37.359+0200] {logging_mixin.py:137} INFO - [2025-09-03T20:02:37.358+0200] {dagbag.py:532} INFO - Filling up the DagBag from /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-09-03T20:02:37.375+0200] {logging_mixin.py:137} INFO - [2025-09-03T20:02:37.375+0200] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-09-03T20:02:37.376+0200] {logging_mixin.py:137} INFO - [2025-09-03T20:02:37.376+0200] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-09-03T20:02:37.376+0200] {processor.py:755} WARNING - No viable dags retrieved from /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-09-03T20:02:37.385+0200] {processor.py:175} INFO - Processing /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.032 seconds
[2025-09-03T20:03:27.586+0200] {processor.py:153} INFO - Started process (PID=4179) to work on /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-09-03T20:03:27.587+0200] {processor.py:743} INFO - Processing file /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-09-03T20:03:27.588+0200] {logging_mixin.py:137} INFO - [2025-09-03T20:03:27.588+0200] {dagbag.py:532} INFO - Filling up the DagBag from /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-09-03T20:03:27.603+0200] {logging_mixin.py:137} INFO - [2025-09-03T20:03:27.602+0200] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-09-03T20:03:27.603+0200] {logging_mixin.py:137} INFO - [2025-09-03T20:03:27.603+0200] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-09-03T20:03:27.603+0200] {processor.py:755} WARNING - No viable dags retrieved from /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-09-03T20:03:27.613+0200] {processor.py:175} INFO - Processing /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.031 seconds
[2025-09-03T20:04:14.557+0200] {processor.py:153} INFO - Started process (PID=4221) to work on /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-09-03T20:04:14.559+0200] {processor.py:743} INFO - Processing file /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-09-03T20:04:14.560+0200] {logging_mixin.py:137} INFO - [2025-09-03T20:04:14.560+0200] {dagbag.py:532} INFO - Filling up the DagBag from /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-09-03T20:04:14.573+0200] {logging_mixin.py:137} INFO - [2025-09-03T20:04:14.573+0200] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-09-03T20:04:14.574+0200] {logging_mixin.py:137} INFO - [2025-09-03T20:04:14.574+0200] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-09-03T20:04:14.574+0200] {processor.py:755} WARNING - No viable dags retrieved from /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-09-03T20:04:14.583+0200] {processor.py:175} INFO - Processing /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.029 seconds
[2025-09-03T20:05:12.692+0200] {processor.py:153} INFO - Started process (PID=4275) to work on /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-09-03T20:05:12.695+0200] {processor.py:743} INFO - Processing file /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-09-03T20:05:12.697+0200] {logging_mixin.py:137} INFO - [2025-09-03T20:05:12.696+0200] {dagbag.py:532} INFO - Filling up the DagBag from /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-09-03T20:05:12.730+0200] {logging_mixin.py:137} INFO - [2025-09-03T20:05:12.729+0200] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-09-03T20:05:12.730+0200] {logging_mixin.py:137} INFO - [2025-09-03T20:05:12.730+0200] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-09-03T20:05:12.731+0200] {processor.py:755} WARNING - No viable dags retrieved from /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-09-03T20:05:12.769+0200] {processor.py:175} INFO - Processing /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.083 seconds
[2025-09-03T20:06:03.199+0200] {processor.py:153} INFO - Started process (PID=4324) to work on /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-09-03T20:06:03.201+0200] {processor.py:743} INFO - Processing file /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-09-03T20:06:03.201+0200] {logging_mixin.py:137} INFO - [2025-09-03T20:06:03.201+0200] {dagbag.py:532} INFO - Filling up the DagBag from /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-09-03T20:06:03.222+0200] {logging_mixin.py:137} INFO - [2025-09-03T20:06:03.221+0200] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-09-03T20:06:03.222+0200] {logging_mixin.py:137} INFO - [2025-09-03T20:06:03.222+0200] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-09-03T20:06:03.222+0200] {processor.py:755} WARNING - No viable dags retrieved from /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-09-03T20:06:03.233+0200] {processor.py:175} INFO - Processing /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.038 seconds
[2025-09-03T20:06:49.696+0200] {processor.py:153} INFO - Started process (PID=4370) to work on /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-09-03T20:06:49.698+0200] {processor.py:743} INFO - Processing file /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-09-03T20:06:49.699+0200] {logging_mixin.py:137} INFO - [2025-09-03T20:06:49.699+0200] {dagbag.py:532} INFO - Filling up the DagBag from /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-09-03T20:06:49.723+0200] {logging_mixin.py:137} INFO - [2025-09-03T20:06:49.722+0200] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-09-03T20:06:49.724+0200] {logging_mixin.py:137} INFO - [2025-09-03T20:06:49.724+0200] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-09-03T20:06:49.724+0200] {processor.py:755} WARNING - No viable dags retrieved from /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-09-03T20:06:49.737+0200] {processor.py:175} INFO - Processing /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.048 seconds
[2025-09-03T20:07:39.797+0200] {processor.py:153} INFO - Started process (PID=4432) to work on /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-09-03T20:07:39.799+0200] {processor.py:743} INFO - Processing file /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-09-03T20:07:39.799+0200] {logging_mixin.py:137} INFO - [2025-09-03T20:07:39.799+0200] {dagbag.py:532} INFO - Filling up the DagBag from /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-09-03T20:07:39.825+0200] {logging_mixin.py:137} INFO - [2025-09-03T20:07:39.824+0200] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-09-03T20:07:39.826+0200] {logging_mixin.py:137} INFO - [2025-09-03T20:07:39.825+0200] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-09-03T20:07:39.826+0200] {processor.py:755} WARNING - No viable dags retrieved from /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-09-03T20:07:39.845+0200] {processor.py:175} INFO - Processing /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.051 seconds
[2025-09-03T20:08:27.683+0200] {processor.py:153} INFO - Started process (PID=4476) to work on /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-09-03T20:08:27.686+0200] {processor.py:743} INFO - Processing file /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-09-03T20:08:27.688+0200] {logging_mixin.py:137} INFO - [2025-09-03T20:08:27.687+0200] {dagbag.py:532} INFO - Filling up the DagBag from /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-09-03T20:08:27.726+0200] {logging_mixin.py:137} INFO - [2025-09-03T20:08:27.725+0200] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-09-03T20:08:27.726+0200] {logging_mixin.py:137} INFO - [2025-09-03T20:08:27.726+0200] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-09-03T20:08:27.727+0200] {processor.py:755} WARNING - No viable dags retrieved from /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-09-03T20:08:27.748+0200] {processor.py:175} INFO - Processing /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.074 seconds
[2025-09-03T20:09:44.278+0200] {processor.py:153} INFO - Started process (PID=4535) to work on /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-09-03T20:09:44.279+0200] {processor.py:743} INFO - Processing file /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-09-03T20:09:44.280+0200] {logging_mixin.py:137} INFO - [2025-09-03T20:09:44.280+0200] {dagbag.py:532} INFO - Filling up the DagBag from /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-09-03T20:09:44.302+0200] {logging_mixin.py:137} INFO - [2025-09-03T20:09:44.300+0200] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-09-03T20:09:44.302+0200] {logging_mixin.py:137} INFO - [2025-09-03T20:09:44.302+0200] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-09-03T20:09:44.303+0200] {processor.py:755} WARNING - No viable dags retrieved from /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-09-03T20:09:44.313+0200] {processor.py:175} INFO - Processing /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.040 seconds
[2025-09-03T20:10:34.085+0200] {processor.py:153} INFO - Started process (PID=4577) to work on /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-09-03T20:10:34.087+0200] {processor.py:743} INFO - Processing file /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-09-03T20:10:34.087+0200] {logging_mixin.py:137} INFO - [2025-09-03T20:10:34.087+0200] {dagbag.py:532} INFO - Filling up the DagBag from /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-09-03T20:10:34.106+0200] {logging_mixin.py:137} INFO - [2025-09-03T20:10:34.105+0200] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-09-03T20:10:34.106+0200] {logging_mixin.py:137} INFO - [2025-09-03T20:10:34.106+0200] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-09-03T20:10:34.106+0200] {processor.py:755} WARNING - No viable dags retrieved from /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-09-03T20:10:34.120+0200] {processor.py:175} INFO - Processing /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.038 seconds
[2025-09-03T20:11:19.036+0200] {processor.py:153} INFO - Started process (PID=4619) to work on /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-09-03T20:11:19.038+0200] {processor.py:743} INFO - Processing file /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-09-03T20:11:19.039+0200] {logging_mixin.py:137} INFO - [2025-09-03T20:11:19.039+0200] {dagbag.py:532} INFO - Filling up the DagBag from /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-09-03T20:11:19.057+0200] {logging_mixin.py:137} INFO - [2025-09-03T20:11:19.057+0200] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-09-03T20:11:19.057+0200] {logging_mixin.py:137} INFO - [2025-09-03T20:11:19.057+0200] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-09-03T20:11:19.058+0200] {processor.py:755} WARNING - No viable dags retrieved from /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-09-03T20:11:19.066+0200] {processor.py:175} INFO - Processing /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.034 seconds
[2025-09-03T20:12:02.906+0200] {processor.py:153} INFO - Started process (PID=4661) to work on /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-09-03T20:12:02.908+0200] {processor.py:743} INFO - Processing file /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-09-03T20:12:02.908+0200] {logging_mixin.py:137} INFO - [2025-09-03T20:12:02.908+0200] {dagbag.py:532} INFO - Filling up the DagBag from /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-09-03T20:12:02.926+0200] {logging_mixin.py:137} INFO - [2025-09-03T20:12:02.925+0200] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-09-03T20:12:02.926+0200] {logging_mixin.py:137} INFO - [2025-09-03T20:12:02.926+0200] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-09-03T20:12:02.926+0200] {processor.py:755} WARNING - No viable dags retrieved from /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-09-03T20:12:02.936+0200] {processor.py:175} INFO - Processing /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.032 seconds
[2025-09-03T20:12:49.537+0200] {processor.py:153} INFO - Started process (PID=4704) to work on /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-09-03T20:12:49.539+0200] {processor.py:743} INFO - Processing file /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-09-03T20:12:49.540+0200] {logging_mixin.py:137} INFO - [2025-09-03T20:12:49.540+0200] {dagbag.py:532} INFO - Filling up the DagBag from /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-09-03T20:12:49.558+0200] {logging_mixin.py:137} INFO - [2025-09-03T20:12:49.557+0200] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-09-03T20:12:49.558+0200] {logging_mixin.py:137} INFO - [2025-09-03T20:12:49.558+0200] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-09-03T20:12:49.558+0200] {processor.py:755} WARNING - No viable dags retrieved from /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-09-03T20:12:49.570+0200] {processor.py:175} INFO - Processing /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.036 seconds
[2025-09-03T20:13:39.527+0200] {processor.py:153} INFO - Started process (PID=4746) to work on /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-09-03T20:13:39.529+0200] {processor.py:743} INFO - Processing file /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-09-03T20:13:39.529+0200] {logging_mixin.py:137} INFO - [2025-09-03T20:13:39.529+0200] {dagbag.py:532} INFO - Filling up the DagBag from /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-09-03T20:13:39.543+0200] {logging_mixin.py:137} INFO - [2025-09-03T20:13:39.542+0200] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-09-03T20:13:39.543+0200] {logging_mixin.py:137} INFO - [2025-09-03T20:13:39.543+0200] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-09-03T20:13:39.543+0200] {processor.py:755} WARNING - No viable dags retrieved from /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-09-03T20:13:39.553+0200] {processor.py:175} INFO - Processing /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.029 seconds
[2025-09-03T20:14:24.790+0200] {processor.py:153} INFO - Started process (PID=4788) to work on /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-09-03T20:14:24.792+0200] {processor.py:743} INFO - Processing file /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-09-03T20:14:24.793+0200] {logging_mixin.py:137} INFO - [2025-09-03T20:14:24.792+0200] {dagbag.py:532} INFO - Filling up the DagBag from /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-09-03T20:14:24.806+0200] {logging_mixin.py:137} INFO - [2025-09-03T20:14:24.806+0200] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-09-03T20:14:24.807+0200] {logging_mixin.py:137} INFO - [2025-09-03T20:14:24.807+0200] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-09-03T20:14:24.807+0200] {processor.py:755} WARNING - No viable dags retrieved from /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-09-03T20:14:24.816+0200] {processor.py:175} INFO - Processing /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.031 seconds
[2025-09-03T20:15:06.266+0200] {processor.py:153} INFO - Started process (PID=4830) to work on /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-09-03T20:15:06.267+0200] {processor.py:743} INFO - Processing file /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-09-03T20:15:06.268+0200] {logging_mixin.py:137} INFO - [2025-09-03T20:15:06.268+0200] {dagbag.py:532} INFO - Filling up the DagBag from /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-09-03T20:15:06.285+0200] {logging_mixin.py:137} INFO - [2025-09-03T20:15:06.285+0200] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-09-03T20:15:06.285+0200] {logging_mixin.py:137} INFO - [2025-09-03T20:15:06.285+0200] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-09-03T20:15:06.286+0200] {processor.py:755} WARNING - No viable dags retrieved from /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-09-03T20:15:06.298+0200] {processor.py:175} INFO - Processing /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.036 seconds
[2025-09-03T20:15:50.976+0200] {processor.py:153} INFO - Started process (PID=4872) to work on /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-09-03T20:15:50.978+0200] {processor.py:743} INFO - Processing file /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-09-03T20:15:50.978+0200] {logging_mixin.py:137} INFO - [2025-09-03T20:15:50.978+0200] {dagbag.py:532} INFO - Filling up the DagBag from /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-09-03T20:15:50.991+0200] {logging_mixin.py:137} INFO - [2025-09-03T20:15:50.990+0200] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-09-03T20:15:50.991+0200] {logging_mixin.py:137} INFO - [2025-09-03T20:15:50.991+0200] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-09-03T20:15:50.992+0200] {processor.py:755} WARNING - No viable dags retrieved from /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-09-03T20:15:51.000+0200] {processor.py:175} INFO - Processing /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.027 seconds
[2025-09-03T20:16:39.752+0200] {processor.py:153} INFO - Started process (PID=4914) to work on /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-09-03T20:16:39.754+0200] {processor.py:743} INFO - Processing file /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-09-03T20:16:39.755+0200] {logging_mixin.py:137} INFO - [2025-09-03T20:16:39.755+0200] {dagbag.py:532} INFO - Filling up the DagBag from /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-09-03T20:16:39.768+0200] {logging_mixin.py:137} INFO - [2025-09-03T20:16:39.768+0200] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-09-03T20:16:39.769+0200] {logging_mixin.py:137} INFO - [2025-09-03T20:16:39.768+0200] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-09-03T20:16:39.769+0200] {processor.py:755} WARNING - No viable dags retrieved from /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-09-03T20:16:39.776+0200] {processor.py:175} INFO - Processing /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.027 seconds
[2025-09-03T20:17:25.707+0200] {processor.py:153} INFO - Started process (PID=4959) to work on /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-09-03T20:17:25.708+0200] {processor.py:743} INFO - Processing file /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-09-03T20:17:25.709+0200] {logging_mixin.py:137} INFO - [2025-09-03T20:17:25.709+0200] {dagbag.py:532} INFO - Filling up the DagBag from /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-09-03T20:17:25.723+0200] {logging_mixin.py:137} INFO - [2025-09-03T20:17:25.723+0200] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-09-03T20:17:25.724+0200] {logging_mixin.py:137} INFO - [2025-09-03T20:17:25.724+0200] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-09-03T20:17:25.724+0200] {processor.py:755} WARNING - No viable dags retrieved from /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-09-03T20:17:25.734+0200] {processor.py:175} INFO - Processing /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.030 seconds
[2025-09-03T20:18:09.339+0200] {processor.py:153} INFO - Started process (PID=5001) to work on /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-09-03T20:18:09.341+0200] {processor.py:743} INFO - Processing file /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-09-03T20:18:09.341+0200] {logging_mixin.py:137} INFO - [2025-09-03T20:18:09.341+0200] {dagbag.py:532} INFO - Filling up the DagBag from /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-09-03T20:18:09.357+0200] {logging_mixin.py:137} INFO - [2025-09-03T20:18:09.356+0200] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-09-03T20:18:09.357+0200] {logging_mixin.py:137} INFO - [2025-09-03T20:18:09.357+0200] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-09-03T20:18:09.357+0200] {processor.py:755} WARNING - No viable dags retrieved from /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-09-03T20:18:09.366+0200] {processor.py:175} INFO - Processing /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.030 seconds
[2025-09-03T20:18:59.795+0200] {processor.py:153} INFO - Started process (PID=5044) to work on /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-09-03T20:18:59.797+0200] {processor.py:743} INFO - Processing file /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-09-03T20:18:59.797+0200] {logging_mixin.py:137} INFO - [2025-09-03T20:18:59.797+0200] {dagbag.py:532} INFO - Filling up the DagBag from /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-09-03T20:18:59.810+0200] {logging_mixin.py:137} INFO - [2025-09-03T20:18:59.810+0200] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-09-03T20:18:59.810+0200] {logging_mixin.py:137} INFO - [2025-09-03T20:18:59.810+0200] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-09-03T20:18:59.811+0200] {processor.py:755} WARNING - No viable dags retrieved from /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-09-03T20:18:59.818+0200] {processor.py:175} INFO - Processing /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.026 seconds
[2025-09-03T20:19:48.418+0200] {processor.py:153} INFO - Started process (PID=5086) to work on /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-09-03T20:19:48.420+0200] {processor.py:743} INFO - Processing file /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-09-03T20:19:48.420+0200] {logging_mixin.py:137} INFO - [2025-09-03T20:19:48.420+0200] {dagbag.py:532} INFO - Filling up the DagBag from /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-09-03T20:19:48.435+0200] {logging_mixin.py:137} INFO - [2025-09-03T20:19:48.435+0200] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-09-03T20:19:48.435+0200] {logging_mixin.py:137} INFO - [2025-09-03T20:19:48.435+0200] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-09-03T20:19:48.436+0200] {processor.py:755} WARNING - No viable dags retrieved from /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-09-03T20:19:48.445+0200] {processor.py:175} INFO - Processing /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.030 seconds
[2025-09-03T20:20:41.825+0200] {processor.py:153} INFO - Started process (PID=5128) to work on /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-09-03T20:20:41.827+0200] {processor.py:743} INFO - Processing file /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-09-03T20:20:41.828+0200] {logging_mixin.py:137} INFO - [2025-09-03T20:20:41.828+0200] {dagbag.py:532} INFO - Filling up the DagBag from /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-09-03T20:20:41.842+0200] {logging_mixin.py:137} INFO - [2025-09-03T20:20:41.842+0200] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-09-03T20:20:41.843+0200] {logging_mixin.py:137} INFO - [2025-09-03T20:20:41.842+0200] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-09-03T20:20:41.843+0200] {processor.py:755} WARNING - No viable dags retrieved from /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-09-03T20:20:41.852+0200] {processor.py:175} INFO - Processing /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.030 seconds
[2025-09-03T20:21:31.265+0200] {processor.py:153} INFO - Started process (PID=5170) to work on /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-09-03T20:21:31.268+0200] {processor.py:743} INFO - Processing file /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-09-03T20:21:31.268+0200] {logging_mixin.py:137} INFO - [2025-09-03T20:21:31.268+0200] {dagbag.py:532} INFO - Filling up the DagBag from /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-09-03T20:21:31.281+0200] {logging_mixin.py:137} INFO - [2025-09-03T20:21:31.281+0200] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-09-03T20:21:31.281+0200] {logging_mixin.py:137} INFO - [2025-09-03T20:21:31.281+0200] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-09-03T20:21:31.281+0200] {processor.py:755} WARNING - No viable dags retrieved from /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-09-03T20:21:31.290+0200] {processor.py:175} INFO - Processing /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.028 seconds
[2025-09-03T20:22:22.057+0200] {processor.py:153} INFO - Started process (PID=5212) to work on /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-09-03T20:22:22.059+0200] {processor.py:743} INFO - Processing file /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-09-03T20:22:22.059+0200] {logging_mixin.py:137} INFO - [2025-09-03T20:22:22.059+0200] {dagbag.py:532} INFO - Filling up the DagBag from /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-09-03T20:22:22.075+0200] {logging_mixin.py:137} INFO - [2025-09-03T20:22:22.074+0200] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-09-03T20:22:22.075+0200] {logging_mixin.py:137} INFO - [2025-09-03T20:22:22.075+0200] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-09-03T20:22:22.075+0200] {processor.py:755} WARNING - No viable dags retrieved from /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-09-03T20:22:22.225+0200] {processor.py:175} INFO - Processing /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.172 seconds
[2025-09-03T20:23:13.849+0200] {processor.py:153} INFO - Started process (PID=5254) to work on /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-09-03T20:23:13.851+0200] {processor.py:743} INFO - Processing file /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-09-03T20:23:13.852+0200] {logging_mixin.py:137} INFO - [2025-09-03T20:23:13.851+0200] {dagbag.py:532} INFO - Filling up the DagBag from /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-09-03T20:23:13.973+0200] {logging_mixin.py:137} INFO - [2025-09-03T20:23:13.973+0200] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-09-03T20:23:13.973+0200] {logging_mixin.py:137} INFO - [2025-09-03T20:23:13.973+0200] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-09-03T20:23:13.973+0200] {processor.py:755} WARNING - No viable dags retrieved from /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-09-03T20:23:13.981+0200] {processor.py:175} INFO - Processing /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.136 seconds
[2025-09-03T20:23:59.511+0200] {processor.py:153} INFO - Started process (PID=5297) to work on /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-09-03T20:23:59.513+0200] {processor.py:743} INFO - Processing file /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-09-03T20:23:59.513+0200] {logging_mixin.py:137} INFO - [2025-09-03T20:23:59.513+0200] {dagbag.py:532} INFO - Filling up the DagBag from /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-09-03T20:23:59.526+0200] {logging_mixin.py:137} INFO - [2025-09-03T20:23:59.526+0200] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-09-03T20:23:59.527+0200] {logging_mixin.py:137} INFO - [2025-09-03T20:23:59.526+0200] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-09-03T20:23:59.527+0200] {processor.py:755} WARNING - No viable dags retrieved from /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-09-03T20:23:59.534+0200] {processor.py:175} INFO - Processing /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.027 seconds
[2025-09-03T20:24:45.870+0200] {processor.py:153} INFO - Started process (PID=5339) to work on /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-09-03T20:24:45.872+0200] {processor.py:743} INFO - Processing file /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-09-03T20:24:45.874+0200] {logging_mixin.py:137} INFO - [2025-09-03T20:24:45.873+0200] {dagbag.py:532} INFO - Filling up the DagBag from /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-09-03T20:24:45.887+0200] {logging_mixin.py:137} INFO - [2025-09-03T20:24:45.886+0200] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-09-03T20:24:45.887+0200] {logging_mixin.py:137} INFO - [2025-09-03T20:24:45.887+0200] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-09-03T20:24:45.887+0200] {processor.py:755} WARNING - No viable dags retrieved from /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-09-03T20:24:45.896+0200] {processor.py:175} INFO - Processing /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.029 seconds
[2025-09-03T20:25:32.914+0200] {processor.py:153} INFO - Started process (PID=5381) to work on /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-09-03T20:25:32.916+0200] {processor.py:743} INFO - Processing file /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-09-03T20:25:32.917+0200] {logging_mixin.py:137} INFO - [2025-09-03T20:25:32.917+0200] {dagbag.py:532} INFO - Filling up the DagBag from /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-09-03T20:25:32.935+0200] {logging_mixin.py:137} INFO - [2025-09-03T20:25:32.934+0200] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-09-03T20:25:32.936+0200] {logging_mixin.py:137} INFO - [2025-09-03T20:25:32.935+0200] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-09-03T20:25:32.936+0200] {processor.py:755} WARNING - No viable dags retrieved from /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-09-03T20:25:32.949+0200] {processor.py:175} INFO - Processing /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.039 seconds
[2025-09-03T20:26:16.814+0200] {processor.py:153} INFO - Started process (PID=5423) to work on /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-09-03T20:26:16.816+0200] {processor.py:743} INFO - Processing file /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-09-03T20:26:16.817+0200] {logging_mixin.py:137} INFO - [2025-09-03T20:26:16.816+0200] {dagbag.py:532} INFO - Filling up the DagBag from /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-09-03T20:26:16.830+0200] {logging_mixin.py:137} INFO - [2025-09-03T20:26:16.829+0200] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-09-03T20:26:16.830+0200] {logging_mixin.py:137} INFO - [2025-09-03T20:26:16.830+0200] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-09-03T20:26:16.830+0200] {processor.py:755} WARNING - No viable dags retrieved from /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-09-03T20:26:16.838+0200] {processor.py:175} INFO - Processing /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.027 seconds
[2025-09-03T20:27:03.076+0200] {processor.py:153} INFO - Started process (PID=5465) to work on /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-09-03T20:27:03.078+0200] {processor.py:743} INFO - Processing file /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-09-03T20:27:03.079+0200] {logging_mixin.py:137} INFO - [2025-09-03T20:27:03.078+0200] {dagbag.py:532} INFO - Filling up the DagBag from /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-09-03T20:27:03.092+0200] {logging_mixin.py:137} INFO - [2025-09-03T20:27:03.091+0200] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-09-03T20:27:03.092+0200] {logging_mixin.py:137} INFO - [2025-09-03T20:27:03.092+0200] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-09-03T20:27:03.092+0200] {processor.py:755} WARNING - No viable dags retrieved from /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-09-03T20:27:03.100+0200] {processor.py:175} INFO - Processing /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.026 seconds
[2025-09-03T20:27:53.466+0200] {processor.py:153} INFO - Started process (PID=5507) to work on /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-09-03T20:27:53.467+0200] {processor.py:743} INFO - Processing file /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-09-03T20:27:53.468+0200] {logging_mixin.py:137} INFO - [2025-09-03T20:27:53.468+0200] {dagbag.py:532} INFO - Filling up the DagBag from /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-09-03T20:27:53.482+0200] {logging_mixin.py:137} INFO - [2025-09-03T20:27:53.481+0200] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-09-03T20:27:53.482+0200] {logging_mixin.py:137} INFO - [2025-09-03T20:27:53.482+0200] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-09-03T20:27:53.482+0200] {processor.py:755} WARNING - No viable dags retrieved from /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-09-03T20:27:53.492+0200] {processor.py:175} INFO - Processing /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.029 seconds
[2025-09-03T20:28:38.529+0200] {processor.py:153} INFO - Started process (PID=5549) to work on /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-09-03T20:28:38.531+0200] {processor.py:743} INFO - Processing file /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-09-03T20:28:38.531+0200] {logging_mixin.py:137} INFO - [2025-09-03T20:28:38.531+0200] {dagbag.py:532} INFO - Filling up the DagBag from /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-09-03T20:28:38.545+0200] {logging_mixin.py:137} INFO - [2025-09-03T20:28:38.544+0200] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-09-03T20:28:38.545+0200] {logging_mixin.py:137} INFO - [2025-09-03T20:28:38.545+0200] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-09-03T20:28:38.545+0200] {processor.py:755} WARNING - No viable dags retrieved from /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-09-03T20:28:38.553+0200] {processor.py:175} INFO - Processing /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.027 seconds
[2025-09-03T20:29:24.937+0200] {processor.py:153} INFO - Started process (PID=5592) to work on /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-09-03T20:29:24.938+0200] {processor.py:743} INFO - Processing file /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-09-03T20:29:24.940+0200] {logging_mixin.py:137} INFO - [2025-09-03T20:29:24.939+0200] {dagbag.py:532} INFO - Filling up the DagBag from /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-09-03T20:29:24.954+0200] {logging_mixin.py:137} INFO - [2025-09-03T20:29:24.953+0200] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-09-03T20:29:24.954+0200] {logging_mixin.py:137} INFO - [2025-09-03T20:29:24.954+0200] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-09-03T20:29:24.954+0200] {processor.py:755} WARNING - No viable dags retrieved from /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-09-03T20:29:24.962+0200] {processor.py:175} INFO - Processing /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.029 seconds
[2025-09-03T20:30:10.150+0200] {processor.py:153} INFO - Started process (PID=5634) to work on /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-09-03T20:30:10.151+0200] {processor.py:743} INFO - Processing file /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-09-03T20:30:10.152+0200] {logging_mixin.py:137} INFO - [2025-09-03T20:30:10.152+0200] {dagbag.py:532} INFO - Filling up the DagBag from /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-09-03T20:30:10.167+0200] {logging_mixin.py:137} INFO - [2025-09-03T20:30:10.166+0200] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-09-03T20:30:10.167+0200] {logging_mixin.py:137} INFO - [2025-09-03T20:30:10.167+0200] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-09-03T20:30:10.167+0200] {processor.py:755} WARNING - No viable dags retrieved from /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-09-03T20:30:10.175+0200] {processor.py:175} INFO - Processing /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.029 seconds
[2025-09-03T20:30:57.991+0200] {processor.py:153} INFO - Started process (PID=5676) to work on /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-09-03T20:30:57.993+0200] {processor.py:743} INFO - Processing file /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-09-03T20:30:57.994+0200] {logging_mixin.py:137} INFO - [2025-09-03T20:30:57.994+0200] {dagbag.py:532} INFO - Filling up the DagBag from /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-09-03T20:30:58.013+0200] {logging_mixin.py:137} INFO - [2025-09-03T20:30:58.012+0200] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-09-03T20:30:58.013+0200] {logging_mixin.py:137} INFO - [2025-09-03T20:30:58.013+0200] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-09-03T20:30:58.013+0200] {processor.py:755} WARNING - No viable dags retrieved from /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-09-03T20:30:58.025+0200] {processor.py:175} INFO - Processing /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.037 seconds
[2025-09-03T20:31:42.851+0200] {processor.py:153} INFO - Started process (PID=5718) to work on /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-09-03T20:31:42.853+0200] {processor.py:743} INFO - Processing file /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-09-03T20:31:42.853+0200] {logging_mixin.py:137} INFO - [2025-09-03T20:31:42.853+0200] {dagbag.py:532} INFO - Filling up the DagBag from /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-09-03T20:31:42.871+0200] {logging_mixin.py:137} INFO - [2025-09-03T20:31:42.870+0200] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-09-03T20:31:42.871+0200] {logging_mixin.py:137} INFO - [2025-09-03T20:31:42.871+0200] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-09-03T20:31:42.871+0200] {processor.py:755} WARNING - No viable dags retrieved from /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-09-03T20:31:42.882+0200] {processor.py:175} INFO - Processing /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.036 seconds
[2025-09-03T20:32:27.015+0200] {processor.py:153} INFO - Started process (PID=5760) to work on /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-09-03T20:32:27.017+0200] {processor.py:743} INFO - Processing file /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-09-03T20:32:27.018+0200] {logging_mixin.py:137} INFO - [2025-09-03T20:32:27.018+0200] {dagbag.py:532} INFO - Filling up the DagBag from /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-09-03T20:32:27.031+0200] {logging_mixin.py:137} INFO - [2025-09-03T20:32:27.031+0200] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-09-03T20:32:27.031+0200] {logging_mixin.py:137} INFO - [2025-09-03T20:32:27.031+0200] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-09-03T20:32:27.031+0200] {processor.py:755} WARNING - No viable dags retrieved from /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-09-03T20:32:27.039+0200] {processor.py:175} INFO - Processing /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.027 seconds
[2025-09-03T20:33:16.298+0200] {processor.py:153} INFO - Started process (PID=5802) to work on /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-09-03T20:33:16.300+0200] {processor.py:743} INFO - Processing file /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-09-03T20:33:16.300+0200] {logging_mixin.py:137} INFO - [2025-09-03T20:33:16.300+0200] {dagbag.py:532} INFO - Filling up the DagBag from /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-09-03T20:33:16.313+0200] {logging_mixin.py:137} INFO - [2025-09-03T20:33:16.313+0200] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-09-03T20:33:16.314+0200] {logging_mixin.py:137} INFO - [2025-09-03T20:33:16.313+0200] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-09-03T20:33:16.314+0200] {processor.py:755} WARNING - No viable dags retrieved from /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-09-03T20:33:16.321+0200] {processor.py:175} INFO - Processing /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.026 seconds
[2025-09-03T20:34:03.169+0200] {processor.py:153} INFO - Started process (PID=5844) to work on /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-09-03T20:34:03.171+0200] {processor.py:743} INFO - Processing file /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-09-03T20:34:03.171+0200] {logging_mixin.py:137} INFO - [2025-09-03T20:34:03.171+0200] {dagbag.py:532} INFO - Filling up the DagBag from /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-09-03T20:34:03.184+0200] {logging_mixin.py:137} INFO - [2025-09-03T20:34:03.184+0200] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-09-03T20:34:03.184+0200] {logging_mixin.py:137} INFO - [2025-09-03T20:34:03.184+0200] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-09-03T20:34:03.184+0200] {processor.py:755} WARNING - No viable dags retrieved from /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-09-03T20:34:03.193+0200] {processor.py:175} INFO - Processing /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.026 seconds
[2025-09-03T20:34:46.679+0200] {processor.py:153} INFO - Started process (PID=5886) to work on /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-09-03T20:34:46.681+0200] {processor.py:743} INFO - Processing file /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-09-03T20:34:46.681+0200] {logging_mixin.py:137} INFO - [2025-09-03T20:34:46.681+0200] {dagbag.py:532} INFO - Filling up the DagBag from /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-09-03T20:34:46.695+0200] {logging_mixin.py:137} INFO - [2025-09-03T20:34:46.695+0200] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-09-03T20:34:46.695+0200] {logging_mixin.py:137} INFO - [2025-09-03T20:34:46.695+0200] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-09-03T20:34:46.695+0200] {processor.py:755} WARNING - No viable dags retrieved from /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-09-03T20:34:46.704+0200] {processor.py:175} INFO - Processing /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.031 seconds
[2025-09-03T20:35:32.582+0200] {processor.py:153} INFO - Started process (PID=5929) to work on /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-09-03T20:35:32.584+0200] {processor.py:743} INFO - Processing file /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-09-03T20:35:32.584+0200] {logging_mixin.py:137} INFO - [2025-09-03T20:35:32.584+0200] {dagbag.py:532} INFO - Filling up the DagBag from /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-09-03T20:35:32.598+0200] {logging_mixin.py:137} INFO - [2025-09-03T20:35:32.597+0200] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-09-03T20:35:32.598+0200] {logging_mixin.py:137} INFO - [2025-09-03T20:35:32.598+0200] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-09-03T20:35:32.598+0200] {processor.py:755} WARNING - No viable dags retrieved from /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-09-03T20:35:32.606+0200] {processor.py:175} INFO - Processing /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.027 seconds
[2025-09-03T20:36:20.206+0200] {processor.py:153} INFO - Started process (PID=5971) to work on /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-09-03T20:36:20.208+0200] {processor.py:743} INFO - Processing file /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-09-03T20:36:20.209+0200] {logging_mixin.py:137} INFO - [2025-09-03T20:36:20.209+0200] {dagbag.py:532} INFO - Filling up the DagBag from /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-09-03T20:36:20.224+0200] {logging_mixin.py:137} INFO - [2025-09-03T20:36:20.223+0200] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-09-03T20:36:20.224+0200] {logging_mixin.py:137} INFO - [2025-09-03T20:36:20.224+0200] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-09-03T20:36:20.224+0200] {processor.py:755} WARNING - No viable dags retrieved from /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-09-03T20:36:20.233+0200] {processor.py:175} INFO - Processing /home/varun/miniconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.030 seconds
